// The following is a list of messages that are used across multiple resource subtypes

// @generated by protoc-gen-es v1.10.0
// @generated from file common/v1/common.proto (package viam.common.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { MethodOptions, proto3, Struct, Timestamp, Value } from "@bufbuild/protobuf";

/**
 * @generated from enum viam.common.v1.KinematicsFileFormat
 */
export const KinematicsFileFormat = /*@__PURE__*/ proto3.makeEnum(
  "viam.common.v1.KinematicsFileFormat",
  [
    {no: 0, name: "KINEMATICS_FILE_FORMAT_UNSPECIFIED", localName: "UNSPECIFIED"},
    {no: 1, name: "KINEMATICS_FILE_FORMAT_SVA", localName: "SVA"},
    {no: 2, name: "KINEMATICS_FILE_FORMAT_URDF", localName: "URDF"},
  ],
);

/**
 * @generated from message viam.common.v1.ResourceName
 */
export const ResourceName = /*@__PURE__*/ proto3.makeMessageType(
  "viam.common.v1.ResourceName",
  () => [
    { no: 1, name: "namespace", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "type", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "subtype", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * Pose is a combination of location and orientation.
 * Location is expressed as distance which is represented by x , y, z coordinates. Orientation is expressed as an orientation vector which
 * is represented by o_x, o_y, o_z and theta. The o_x, o_y, o_z coordinates represent the point on the cartesian unit sphere that the end of
 * the arm is pointing to (with the origin as reference). That unit vector forms an axis around which theta rotates. This means that
 * incrementing / decrementing theta will perform an inline rotation of the end effector.
 * Theta is defined as rotation between two planes: the first being defined by the origin, the point (0,0,1), and the rx, ry, rz point, and the
 * second being defined by the origin, the rx, ry, rz point and the local Z axis. Therefore, if theta is kept at zero as the north/south pole
 * is circled, the Roll will correct itself to remain in-line. 
 *
 * @generated from message viam.common.v1.Pose
 */
export const Pose = /*@__PURE__*/ proto3.makeMessageType(
  "viam.common.v1.Pose",
  () => [
    { no: 1, name: "x", kind: "scalar", T: 1 /* ScalarType.DOUBLE */ },
    { no: 2, name: "y", kind: "scalar", T: 1 /* ScalarType.DOUBLE */ },
    { no: 3, name: "z", kind: "scalar", T: 1 /* ScalarType.DOUBLE */ },
    { no: 4, name: "o_x", kind: "scalar", T: 1 /* ScalarType.DOUBLE */ },
    { no: 5, name: "o_y", kind: "scalar", T: 1 /* ScalarType.DOUBLE */ },
    { no: 6, name: "o_z", kind: "scalar", T: 1 /* ScalarType.DOUBLE */ },
    { no: 7, name: "theta", kind: "scalar", T: 1 /* ScalarType.DOUBLE */ },
  ],
);

/**
 * @generated from message viam.common.v1.Orientation
 */
export const Orientation = /*@__PURE__*/ proto3.makeMessageType(
  "viam.common.v1.Orientation",
  () => [
    { no: 1, name: "o_x", kind: "scalar", T: 1 /* ScalarType.DOUBLE */ },
    { no: 2, name: "o_y", kind: "scalar", T: 1 /* ScalarType.DOUBLE */ },
    { no: 3, name: "o_z", kind: "scalar", T: 1 /* ScalarType.DOUBLE */ },
    { no: 4, name: "theta", kind: "scalar", T: 1 /* ScalarType.DOUBLE */ },
  ],
);

/**
 * @generated from message viam.common.v1.PoseCloud
 */
export const PoseCloud = /*@__PURE__*/ proto3.makeMessageType(
  "viam.common.v1.PoseCloud",
  () => [
    { no: 1, name: "x", kind: "scalar", T: 1 /* ScalarType.DOUBLE */ },
    { no: 2, name: "y", kind: "scalar", T: 1 /* ScalarType.DOUBLE */ },
    { no: 3, name: "z", kind: "scalar", T: 1 /* ScalarType.DOUBLE */ },
    { no: 4, name: "o_x", kind: "scalar", T: 1 /* ScalarType.DOUBLE */ },
    { no: 5, name: "o_y", kind: "scalar", T: 1 /* ScalarType.DOUBLE */ },
    { no: 6, name: "o_z", kind: "scalar", T: 1 /* ScalarType.DOUBLE */ },
    { no: 7, name: "theta", kind: "scalar", T: 1 /* ScalarType.DOUBLE */ },
  ],
);

/**
 * PoseInFrame contains a pose and the reference frame in which it was observed
 *
 * @generated from message viam.common.v1.PoseInFrame
 */
export const PoseInFrame = /*@__PURE__*/ proto3.makeMessageType(
  "viam.common.v1.PoseInFrame",
  () => [
    { no: 1, name: "reference_frame", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "pose", kind: "message", T: Pose },
    { no: 3, name: "goal_cloud", kind: "message", T: PoseCloud, opt: true },
  ],
);

/**
 * @generated from message viam.common.v1.Vector3
 */
export const Vector3 = /*@__PURE__*/ proto3.makeMessageType(
  "viam.common.v1.Vector3",
  () => [
    { no: 1, name: "x", kind: "scalar", T: 1 /* ScalarType.DOUBLE */ },
    { no: 2, name: "y", kind: "scalar", T: 1 /* ScalarType.DOUBLE */ },
    { no: 3, name: "z", kind: "scalar", T: 1 /* ScalarType.DOUBLE */ },
  ],
);

/**
 * @generated from message viam.common.v1.Sphere
 */
export const Sphere = /*@__PURE__*/ proto3.makeMessageType(
  "viam.common.v1.Sphere",
  () => [
    { no: 1, name: "radius_mm", kind: "scalar", T: 1 /* ScalarType.DOUBLE */ },
  ],
);

/**
 * @generated from message viam.common.v1.Capsule
 */
export const Capsule = /*@__PURE__*/ proto3.makeMessageType(
  "viam.common.v1.Capsule",
  () => [
    { no: 1, name: "radius_mm", kind: "scalar", T: 1 /* ScalarType.DOUBLE */ },
    { no: 2, name: "length_mm", kind: "scalar", T: 1 /* ScalarType.DOUBLE */ },
  ],
);

/**
 * RectangularPrism contains a Vector3 field corresponding to the X, Y, Z dimensions of the prism in mms
 * These dimensions are with respect to the referenceframe in which the RectangularPrism is defined
 *
 * @generated from message viam.common.v1.RectangularPrism
 */
export const RectangularPrism = /*@__PURE__*/ proto3.makeMessageType(
  "viam.common.v1.RectangularPrism",
  () => [
    { no: 1, name: "dims_mm", kind: "message", T: Vector3 },
  ],
);

/**
 * @generated from message viam.common.v1.Mesh
 */
export const Mesh = /*@__PURE__*/ proto3.makeMessageType(
  "viam.common.v1.Mesh",
  () => [
    { no: 1, name: "content_type", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "mesh", kind: "scalar", T: 12 /* ScalarType.BYTES */ },
  ],
);

/**
 * @generated from message viam.common.v1.PointCloud
 */
export const PointCloud = /*@__PURE__*/ proto3.makeMessageType(
  "viam.common.v1.PointCloud",
  () => [
    { no: 1, name: "point_cloud", kind: "scalar", T: 12 /* ScalarType.BYTES */ },
  ],
);

/**
 * Geometry contains the dimensions of a given geometry and the pose of its center. The geometry is one of either a sphere or a box.
 *
 * @generated from message viam.common.v1.Geometry
 */
export const Geometry = /*@__PURE__*/ proto3.makeMessageType(
  "viam.common.v1.Geometry",
  () => [
    { no: 1, name: "center", kind: "message", T: Pose },
    { no: 2, name: "sphere", kind: "message", T: Sphere, oneof: "geometry_type" },
    { no: 3, name: "box", kind: "message", T: RectangularPrism, oneof: "geometry_type" },
    { no: 5, name: "capsule", kind: "message", T: Capsule, oneof: "geometry_type" },
    { no: 6, name: "mesh", kind: "message", T: Mesh, oneof: "geometry_type" },
    { no: 7, name: "pointcloud", kind: "message", T: PointCloud, oneof: "geometry_type" },
    { no: 4, name: "label", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * GeometriesinFrame contains the dimensions of a given geometry, pose of its center point, and the reference frame by which it was
 * observed.
 *
 * @generated from message viam.common.v1.GeometriesInFrame
 */
export const GeometriesInFrame = /*@__PURE__*/ proto3.makeMessageType(
  "viam.common.v1.GeometriesInFrame",
  () => [
    { no: 1, name: "reference_frame", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "geometries", kind: "message", T: Geometry, repeated: true },
  ],
);

/**
 * PointCloudObject contains an image in bytes with point cloud data of all of the objects captured by a given observer as well as a
 * repeated list of geometries which respresents the center point and geometry of each of the objects within the point cloud
 *
 * @generated from message viam.common.v1.PointCloudObject
 */
export const PointCloudObject = /*@__PURE__*/ proto3.makeMessageType(
  "viam.common.v1.PointCloudObject",
  () => [
    { no: 1, name: "point_cloud", kind: "scalar", T: 12 /* ScalarType.BYTES */ },
    { no: 2, name: "geometries", kind: "message", T: GeometriesInFrame },
  ],
);

/**
 * @generated from message viam.common.v1.GeoPoint
 */
export const GeoPoint = /*@__PURE__*/ proto3.makeMessageType(
  "viam.common.v1.GeoPoint",
  () => [
    { no: 1, name: "latitude", kind: "scalar", T: 1 /* ScalarType.DOUBLE */ },
    { no: 2, name: "longitude", kind: "scalar", T: 1 /* ScalarType.DOUBLE */ },
  ],
);

/**
 * GeoGeometry contains information describing Geometry(s) that is located at a GeoPoint
 *
 * @generated from message viam.common.v1.GeoGeometry
 */
export const GeoGeometry = /*@__PURE__*/ proto3.makeMessageType(
  "viam.common.v1.GeoGeometry",
  () => [
    { no: 1, name: "location", kind: "message", T: GeoPoint },
    { no: 2, name: "geometries", kind: "message", T: Geometry, repeated: true },
  ],
);

/**
 * Transform contains a pose and two reference frames. The first reference frame is the starting reference frame, and the second reference
 * frame is the observer reference frame. The second reference frame has a pose which represents the pose of an object in the first
 * reference frame as observed within the second reference frame.
 *
 * @generated from message viam.common.v1.Transform
 */
export const Transform = /*@__PURE__*/ proto3.makeMessageType(
  "viam.common.v1.Transform",
  () => [
    { no: 1, name: "reference_frame", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "pose_in_observer_frame", kind: "message", T: PoseInFrame },
    { no: 3, name: "physical_object", kind: "message", T: Geometry, opt: true },
    { no: 4, name: "uuid", kind: "scalar", T: 12 /* ScalarType.BYTES */ },
    { no: 5, name: "metadata", kind: "message", T: Struct, opt: true },
  ],
);

/**
 * WorldState contains information about the physical environment around a given robot. All of the fields within this message are optional,
 * they can include information about the physical dimensions of an obstacle, the freespace of a robot, and any desired transforms between a
 * given reference frame and a new target reference frame.
 *
 * @generated from message viam.common.v1.WorldState
 */
export const WorldState = /*@__PURE__*/ proto3.makeMessageType(
  "viam.common.v1.WorldState",
  () => [
    { no: 1, name: "obstacles", kind: "message", T: GeometriesInFrame, repeated: true },
    { no: 3, name: "transforms", kind: "message", T: Transform, repeated: true },
  ],
);

/**
 * ActuatorStatus is a generic status for resources that only need to return actuator status.
 *
 * @generated from message viam.common.v1.ActuatorStatus
 */
export const ActuatorStatus = /*@__PURE__*/ proto3.makeMessageType(
  "viam.common.v1.ActuatorStatus",
  () => [
    { no: 1, name: "is_moving", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
  ],
);

/**
 * @generated from message viam.common.v1.ResponseMetadata
 */
export const ResponseMetadata = /*@__PURE__*/ proto3.makeMessageType(
  "viam.common.v1.ResponseMetadata",
  () => [
    { no: 1, name: "captured_at", kind: "message", T: Timestamp, opt: true },
  ],
);

/**
 * DoCommandRequest represents a generic DoCommand input
 *
 * @generated from message viam.common.v1.DoCommandRequest
 */
export const DoCommandRequest = /*@__PURE__*/ proto3.makeMessageType(
  "viam.common.v1.DoCommandRequest",
  () => [
    { no: 1, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "command", kind: "message", T: Struct },
  ],
);

/**
 * DoCommandResponse represents a generic DoCommand output
 *
 * @generated from message viam.common.v1.DoCommandResponse
 */
export const DoCommandResponse = /*@__PURE__*/ proto3.makeMessageType(
  "viam.common.v1.DoCommandResponse",
  () => [
    { no: 1, name: "result", kind: "message", T: Struct },
  ],
);

/**
 * GetStatusRequest represents a generic GetStatus input
 *
 * @generated from message viam.common.v1.GetStatusRequest
 */
export const GetStatusRequest = /*@__PURE__*/ proto3.makeMessageType(
  "viam.common.v1.GetStatusRequest",
  () => [
    { no: 1, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * GetStatusResponse represents a generic GetStatus output
 *
 * @generated from message viam.common.v1.GetStatusResponse
 */
export const GetStatusResponse = /*@__PURE__*/ proto3.makeMessageType(
  "viam.common.v1.GetStatusResponse",
  () => [
    { no: 1, name: "result", kind: "message", T: Struct },
  ],
);

/**
 * @generated from message viam.common.v1.GetKinematicsRequest
 */
export const GetKinematicsRequest = /*@__PURE__*/ proto3.makeMessageType(
  "viam.common.v1.GetKinematicsRequest",
  () => [
    { no: 1, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 99, name: "extra", kind: "message", T: Struct },
  ],
);

/**
 * @generated from message viam.common.v1.GetKinematicsResponse
 */
export const GetKinematicsResponse = /*@__PURE__*/ proto3.makeMessageType(
  "viam.common.v1.GetKinematicsResponse",
  () => [
    { no: 1, name: "format", kind: "enum", T: proto3.getEnumType(KinematicsFileFormat) },
    { no: 2, name: "kinematics_data", kind: "scalar", T: 12 /* ScalarType.BYTES */ },
    { no: 3, name: "meshes_by_urdf_filepath", kind: "map", K: 9 /* ScalarType.STRING */, V: {kind: "message", T: Mesh} },
  ],
);

/**
 * @generated from message viam.common.v1.GetGeometriesRequest
 */
export const GetGeometriesRequest = /*@__PURE__*/ proto3.makeMessageType(
  "viam.common.v1.GetGeometriesRequest",
  () => [
    { no: 1, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 99, name: "extra", kind: "message", T: Struct },
  ],
);

/**
 * @generated from message viam.common.v1.GetGeometriesResponse
 */
export const GetGeometriesResponse = /*@__PURE__*/ proto3.makeMessageType(
  "viam.common.v1.GetGeometriesResponse",
  () => [
    { no: 1, name: "geometries", kind: "message", T: Geometry, repeated: true },
  ],
);

/**
 * @generated from message viam.common.v1.Get3DModelsRequest
 */
export const Get3DModelsRequest = /*@__PURE__*/ proto3.makeMessageType(
  "viam.common.v1.Get3DModelsRequest",
  () => [
    { no: 1, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 99, name: "extra", kind: "message", T: Struct },
  ],
);

/**
 * @generated from message viam.common.v1.Get3DModelsResponse
 */
export const Get3DModelsResponse = /*@__PURE__*/ proto3.makeMessageType(
  "viam.common.v1.Get3DModelsResponse",
  () => [
    { no: 1, name: "models", kind: "map", K: 9 /* ScalarType.STRING */, V: {kind: "message", T: Mesh} },
  ],
);

/**
 * @generated from message viam.common.v1.GetReadingsRequest
 */
export const GetReadingsRequest = /*@__PURE__*/ proto3.makeMessageType(
  "viam.common.v1.GetReadingsRequest",
  () => [
    { no: 1, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 99, name: "extra", kind: "message", T: Struct },
  ],
);

/**
 * @generated from message viam.common.v1.GetReadingsResponse
 */
export const GetReadingsResponse = /*@__PURE__*/ proto3.makeMessageType(
  "viam.common.v1.GetReadingsResponse",
  () => [
    { no: 1, name: "readings", kind: "map", K: 9 /* ScalarType.STRING */, V: {kind: "message", T: Value} },
  ],
);

/**
 * @generated from message viam.common.v1.LogEntry
 */
export const LogEntry = /*@__PURE__*/ proto3.makeMessageType(
  "viam.common.v1.LogEntry",
  () => [
    { no: 1, name: "host", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "level", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "time", kind: "message", T: Timestamp },
    { no: 4, name: "logger_name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "message", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 6, name: "caller", kind: "message", T: Struct },
    { no: 7, name: "stack", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 8, name: "fields", kind: "message", T: Struct, repeated: true },
  ],
);

/**
 * Information about an audio stream or device.
 *
 * @generated from message viam.common.v1.AudioInfo
 */
export const AudioInfo = /*@__PURE__*/ proto3.makeMessageType(
  "viam.common.v1.AudioInfo",
  () => [
    { no: 1, name: "codec", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "sample_rate_hz", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 3, name: "num_channels", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ],
);

/**
 * Shared properties for AudioIn and AudioOut components.
 *
 * @generated from message viam.common.v1.GetPropertiesRequest
 */
export const GetPropertiesRequest = /*@__PURE__*/ proto3.makeMessageType(
  "viam.common.v1.GetPropertiesRequest",
  () => [
    { no: 1, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 99, name: "extra", kind: "message", T: Struct },
  ],
);

/**
 * @generated from message viam.common.v1.GetPropertiesResponse
 */
export const GetPropertiesResponse = /*@__PURE__*/ proto3.makeMessageType(
  "viam.common.v1.GetPropertiesResponse",
  () => [
    { no: 1, name: "supported_codecs", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
    { no: 2, name: "sample_rate_hz", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 3, name: "num_channels", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ],
);

/**
 * safety_heartbeat_monitored is used on methods to signify that if a session is in use
 * and the session was the last to call this method, the resource associated with the
 * method will be stopped.
 *
 * @generated from extension: optional bool safety_heartbeat_monitored = 84260;
 */
export const safety_heartbeat_monitored = proto3.makeExtension(
  "viam.common.v1.safety_heartbeat_monitored", 
  MethodOptions, 
  { no: 84260, kind: "scalar", T: 8 /* ScalarType.BOOL */, opt: true },
);

