// @generated by protoc-gen-es v1.10.0
// @generated from file app/datasync/v1/data_sync.proto (package viam.app.datasync.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { Any, proto3, Struct, Timestamp } from "@bufbuild/protobuf";
import { Annotations } from "../../data/v1/data_pb.js";

/**
 * @generated from enum viam.app.datasync.v1.MimeType
 */
export const MimeType = /*@__PURE__*/ proto3.makeEnum(
  "viam.app.datasync.v1.MimeType",
  [
    {no: 0, name: "MIME_TYPE_UNSPECIFIED", localName: "UNSPECIFIED"},
    {no: 1, name: "MIME_TYPE_IMAGE_JPEG", localName: "IMAGE_JPEG"},
    {no: 2, name: "MIME_TYPE_IMAGE_PNG", localName: "IMAGE_PNG"},
    {no: 3, name: "MIME_TYPE_APPLICATION_PCD", localName: "APPLICATION_PCD"},
    {no: 4, name: "MIME_TYPE_VIDEO_MP4", localName: "VIDEO_MP4"},
  ],
);

/**
 * DataType specifies the type of data uploaded.
 *
 * @generated from enum viam.app.datasync.v1.DataType
 */
export const DataType = /*@__PURE__*/ proto3.makeEnum(
  "viam.app.datasync.v1.DataType",
  [
    {no: 0, name: "DATA_TYPE_UNSPECIFIED", localName: "UNSPECIFIED"},
    {no: 1, name: "DATA_TYPE_BINARY_SENSOR", localName: "BINARY_SENSOR"},
    {no: 2, name: "DATA_TYPE_TABULAR_SENSOR", localName: "TABULAR_SENSOR"},
    {no: 3, name: "DATA_TYPE_FILE", localName: "FILE"},
  ],
);

/**
 * DataCaptureUploadRequest requests to upload the contents and metadata for tabular data.
 *
 * @generated from message viam.app.datasync.v1.DataCaptureUploadRequest
 */
export const DataCaptureUploadRequest = /*@__PURE__*/ proto3.makeMessageType(
  "viam.app.datasync.v1.DataCaptureUploadRequest",
  () => [
    { no: 1, name: "metadata", kind: "message", T: UploadMetadata },
    { no: 2, name: "sensor_contents", kind: "message", T: SensorData, repeated: true },
  ],
);

/**
 * DataCaptureUploadResponse returns the file id of the uploaded contents and metadata for tabular data.
 *
 * @generated from message viam.app.datasync.v1.DataCaptureUploadResponse
 */
export const DataCaptureUploadResponse = /*@__PURE__*/ proto3.makeMessageType(
  "viam.app.datasync.v1.DataCaptureUploadResponse",
  () => [
    { no: 1, name: "file_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "binary_data_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * FileUploadRequest requests to upload the contents and metadata for binary (image + file) data.
 * The first packet must be the UploadMetadata associated with the binary data.
 *
 * @generated from message viam.app.datasync.v1.FileUploadRequest
 */
export const FileUploadRequest = /*@__PURE__*/ proto3.makeMessageType(
  "viam.app.datasync.v1.FileUploadRequest",
  () => [
    { no: 1, name: "metadata", kind: "message", T: UploadMetadata, oneof: "upload_packet" },
    { no: 2, name: "file_contents", kind: "message", T: FileData, oneof: "upload_packet" },
  ],
);

/**
 * FileUploadResponse returns the file id of the uploaded contents and metadata for binary (image + file) data.
 *
 * @generated from message viam.app.datasync.v1.FileUploadResponse
 */
export const FileUploadResponse = /*@__PURE__*/ proto3.makeMessageType(
  "viam.app.datasync.v1.FileUploadResponse",
  () => [
    { no: 1, name: "file_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "binary_data_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * StreamingDataCaptureUploadRequest requests to upload the contents and metadata for streaming binary (image + file) data.
 * The first packet must be the DataCaptureUploadMetadata associated with the data.
 *
 * @generated from message viam.app.datasync.v1.StreamingDataCaptureUploadRequest
 */
export const StreamingDataCaptureUploadRequest = /*@__PURE__*/ proto3.makeMessageType(
  "viam.app.datasync.v1.StreamingDataCaptureUploadRequest",
  () => [
    { no: 1, name: "metadata", kind: "message", T: DataCaptureUploadMetadata, oneof: "upload_packet" },
    { no: 2, name: "data", kind: "scalar", T: 12 /* ScalarType.BYTES */, oneof: "upload_packet" },
  ],
);

/**
 * StreamingDataCaptureUploadResponse returns the file id of the uploaded contents and metadata for streaming binary (image + file) data.
 *
 * @generated from message viam.app.datasync.v1.StreamingDataCaptureUploadResponse
 */
export const StreamingDataCaptureUploadResponse = /*@__PURE__*/ proto3.makeMessageType(
  "viam.app.datasync.v1.StreamingDataCaptureUploadResponse",
  () => [
    { no: 1, name: "file_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "binary_data_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * SensorMetadata contains the time the sensor data was requested and was
 * received.
 *
 * @generated from message viam.app.datasync.v1.SensorMetadata
 */
export const SensorMetadata = /*@__PURE__*/ proto3.makeMessageType(
  "viam.app.datasync.v1.SensorMetadata",
  () => [
    { no: 1, name: "time_requested", kind: "message", T: Timestamp },
    { no: 2, name: "time_received", kind: "message", T: Timestamp },
    { no: 3, name: "mime_type", kind: "enum", T: proto3.getEnumType(MimeType) },
    { no: 4, name: "annotations", kind: "message", T: Annotations },
  ],
);

/**
 * SensorData contains the contents and metadata for tabular data.
 *
 * @generated from message viam.app.datasync.v1.SensorData
 */
export const SensorData = /*@__PURE__*/ proto3.makeMessageType(
  "viam.app.datasync.v1.SensorData",
  () => [
    { no: 1, name: "metadata", kind: "message", T: SensorMetadata },
    { no: 2, name: "struct", kind: "message", T: Struct, oneof: "data" },
    { no: 3, name: "binary", kind: "scalar", T: 12 /* ScalarType.BYTES */, oneof: "data" },
  ],
);

/**
 * FileData contains the contents of binary (image + file) data.
 *
 * @generated from message viam.app.datasync.v1.FileData
 */
export const FileData = /*@__PURE__*/ proto3.makeMessageType(
  "viam.app.datasync.v1.FileData",
  () => [
    { no: 1, name: "data", kind: "scalar", T: 12 /* ScalarType.BYTES */ },
  ],
);

/**
 * UploadMetadata contains the metadata for binary (image + file) data.
 *
 * @generated from message viam.app.datasync.v1.UploadMetadata
 */
export const UploadMetadata = /*@__PURE__*/ proto3.makeMessageType(
  "viam.app.datasync.v1.UploadMetadata",
  () => [
    { no: 1, name: "part_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "component_type", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "component_name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "method_name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 6, name: "type", kind: "enum", T: proto3.getEnumType(DataType) },
    { no: 8, name: "method_parameters", kind: "map", K: 9 /* ScalarType.STRING */, V: {kind: "message", T: Any} },
    { no: 7, name: "file_name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 9, name: "file_extension", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 14, name: "file_create_time", kind: "message", T: Timestamp },
    { no: 15, name: "file_modify_time", kind: "message", T: Timestamp },
    { no: 10, name: "tags", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
    { no: 12, name: "dataset_ids", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
    { no: 13, name: "mime_type", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * CaptureInterval specifies the start and end times of the data capture.
 *
 * @generated from message viam.app.datasync.v1.CaptureInterval
 */
export const CaptureInterval = /*@__PURE__*/ proto3.makeMessageType(
  "viam.app.datasync.v1.CaptureInterval",
  () => [
    { no: 1, name: "start", kind: "message", T: Timestamp },
    { no: 2, name: "end", kind: "message", T: Timestamp },
  ],
);

/**
 * DataCaptureMetadata contains the metadata for data captured by collectors.
 *
 * @generated from message viam.app.datasync.v1.DataCaptureMetadata
 */
export const DataCaptureMetadata = /*@__PURE__*/ proto3.makeMessageType(
  "viam.app.datasync.v1.DataCaptureMetadata",
  () => [
    { no: 1, name: "component_type", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "component_name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "method_name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "type", kind: "enum", T: proto3.getEnumType(DataType) },
    { no: 6, name: "method_parameters", kind: "map", K: 9 /* ScalarType.STRING */, V: {kind: "message", T: Any} },
    { no: 7, name: "file_extension", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 8, name: "tags", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
    { no: 10, name: "mime_type", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * DataCaptureUploadMetadata contains the metadata for streaming binary (image + file) data.
 *
 * @generated from message viam.app.datasync.v1.DataCaptureUploadMetadata
 */
export const DataCaptureUploadMetadata = /*@__PURE__*/ proto3.makeMessageType(
  "viam.app.datasync.v1.DataCaptureUploadMetadata",
  () => [
    { no: 1, name: "upload_metadata", kind: "message", T: UploadMetadata },
    { no: 2, name: "sensor_metadata", kind: "message", T: SensorMetadata },
  ],
);

