// @generated by protoc-gen-connect-es v1.6.1
// @generated from file component/generic/v1/generic.proto (package viam.component.generic.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { DoCommandRequest, DoCommandResponse, GetGeometriesRequest, GetGeometriesResponse, GetStatusRequest, GetStatusResponse } from "../../../common/v1/common_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * GenericService services all generic components associated with a robot
 *
 * @generated from service viam.component.generic.v1.GenericService
 */
export const GenericService = {
  typeName: "viam.component.generic.v1.GenericService",
  methods: {
    /**
     * DoCommand sends/receives arbitrary commands
     *
     * @generated from rpc viam.component.generic.v1.GenericService.DoCommand
     */
    doCommand: {
      name: "DoCommand",
      I: DoCommandRequest,
      O: DoCommandResponse,
      kind: MethodKind.Unary,
    },
    /**
     * GetStatus returns the status of the resource
     *
     * @generated from rpc viam.component.generic.v1.GenericService.GetStatus
     */
    getStatus: {
      name: "GetStatus",
      I: GetStatusRequest,
      O: GetStatusResponse,
      kind: MethodKind.Unary,
    },
    /**
     * GetGeometries returns the geometries of the component in their current configuration
     *
     * @generated from rpc viam.component.generic.v1.GenericService.GetGeometries
     */
    getGeometries: {
      name: "GetGeometries",
      I: GetGeometriesRequest,
      O: GetGeometriesResponse,
      kind: MethodKind.Unary,
    },
  }
};

