// @generated by protoc-gen-connect-es v1.6.1
// @generated from file component/audioin/v1/audioin.proto (package viam.component.audioin.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { GetAudioRequest, GetAudioResponse } from "./audioin_pb.js";
import { MethodKind } from "@bufbuild/protobuf";
import { DoCommandRequest, DoCommandResponse, GetGeometriesRequest, GetGeometriesResponse, GetPropertiesRequest, GetPropertiesResponse, GetStatusRequest, GetStatusResponse } from "../../../common/v1/common_pb.js";

/**
 * An AudioInService services all audio inputss associated with a robot
 *
 * @generated from service viam.component.audioin.v1.AudioInService
 */
export declare const AudioInService: {
  readonly typeName: "viam.component.audioin.v1.AudioInService",
  readonly methods: {
    /**
     * GetAudio streams audio from the given audioin
     *
     * @generated from rpc viam.component.audioin.v1.AudioInService.GetAudio
     */
    readonly getAudio: {
      readonly name: "GetAudio",
      readonly I: typeof GetAudioRequest,
      readonly O: typeof GetAudioResponse,
      readonly kind: MethodKind.ServerStreaming,
    },
    /**
     * GetProperties returns the properties of the audioin
     *
     * @generated from rpc viam.component.audioin.v1.AudioInService.GetProperties
     */
    readonly getProperties: {
      readonly name: "GetProperties",
      readonly I: typeof GetPropertiesRequest,
      readonly O: typeof GetPropertiesResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * DoCommand sends/receives arbitrary commands
     *
     * @generated from rpc viam.component.audioin.v1.AudioInService.DoCommand
     */
    readonly doCommand: {
      readonly name: "DoCommand",
      readonly I: typeof DoCommandRequest,
      readonly O: typeof DoCommandResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * GetStatus returns the status of the resource
     *
     * @generated from rpc viam.component.audioin.v1.AudioInService.GetStatus
     */
    readonly getStatus: {
      readonly name: "GetStatus",
      readonly I: typeof GetStatusRequest,
      readonly O: typeof GetStatusResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * GetGeometries returns the geometries of the component in their current configuration
     *
     * @generated from rpc viam.component.audioin.v1.AudioInService.GetGeometries
     */
    readonly getGeometries: {
      readonly name: "GetGeometries",
      readonly I: typeof GetGeometriesRequest,
      readonly O: typeof GetGeometriesResponse,
      readonly kind: MethodKind.Unary,
    },
  }
};

