// @generated by protoc-gen-connect-es v1.6.1
// @generated from file component/inputcontroller/v1/input_controller.proto (package viam.component.inputcontroller.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { GetControlsRequest, GetControlsResponse, GetEventsRequest, GetEventsResponse, StreamEventsRequest, StreamEventsResponse, TriggerEventRequest, TriggerEventResponse } from "./input_controller_pb.js";
import { MethodKind } from "@bufbuild/protobuf";
import { DoCommandRequest, DoCommandResponse, GetGeometriesRequest, GetGeometriesResponse, GetStatusRequest, GetStatusResponse } from "../../../common/v1/common_pb.js";

/**
 * InputControllerService servicestains all input controller associated with a robot
 *
 * @generated from service viam.component.inputcontroller.v1.InputControllerService
 */
export const InputControllerService = {
  typeName: "viam.component.inputcontroller.v1.InputControllerService",
  methods: {
    /**
     * GetControls returns a list of GetControls provided by the Controller
     *
     * @generated from rpc viam.component.inputcontroller.v1.InputControllerService.GetControls
     */
    getControls: {
      name: "GetControls",
      I: GetControlsRequest,
      O: GetControlsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * GetEvents returns a list of events representing the last event on each control of a give Input Controller
     *
     * @generated from rpc viam.component.inputcontroller.v1.InputControllerService.GetEvents
     */
    getEvents: {
      name: "GetEvents",
      I: GetEventsRequest,
      O: GetEventsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * StreamEvents starts a stream of InputControllerEvents for the given controls (buttons/axes) on a robot's input controller
     *
     * @generated from rpc viam.component.inputcontroller.v1.InputControllerService.StreamEvents
     */
    streamEvents: {
      name: "StreamEvents",
      I: StreamEventsRequest,
      O: StreamEventsResponse,
      kind: MethodKind.ServerStreaming,
    },
    /**
     * TriggerEvent, where supported, injects an InputControllerEvent into an input controller to (virtually) generate events
     * like button presses or axis movements
     *
     * @generated from rpc viam.component.inputcontroller.v1.InputControllerService.TriggerEvent
     */
    triggerEvent: {
      name: "TriggerEvent",
      I: TriggerEventRequest,
      O: TriggerEventResponse,
      kind: MethodKind.Unary,
    },
    /**
     * DoCommand sends/receives arbitrary commands
     *
     * @generated from rpc viam.component.inputcontroller.v1.InputControllerService.DoCommand
     */
    doCommand: {
      name: "DoCommand",
      I: DoCommandRequest,
      O: DoCommandResponse,
      kind: MethodKind.Unary,
    },
    /**
     * GetStatus returns the status of the resource
     *
     * @generated from rpc viam.component.inputcontroller.v1.InputControllerService.GetStatus
     */
    getStatus: {
      name: "GetStatus",
      I: GetStatusRequest,
      O: GetStatusResponse,
      kind: MethodKind.Unary,
    },
    /**
     * GetGeometries returns the geometries of the component in their current configuration
     *
     * @generated from rpc viam.component.inputcontroller.v1.InputControllerService.GetGeometries
     */
    getGeometries: {
      name: "GetGeometries",
      I: GetGeometriesRequest,
      O: GetGeometriesResponse,
      kind: MethodKind.Unary,
    },
  }
};

