// @generated by protoc-gen-es v1.10.0
// @generated from file component/inputcontroller/v1/input_controller.proto (package viam.component.inputcontroller.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3, Struct, Timestamp } from "@bufbuild/protobuf";

/**
 * @generated from message viam.component.inputcontroller.v1.GetControlsRequest
 */
export const GetControlsRequest = /*@__PURE__*/ proto3.makeMessageType(
  "viam.component.inputcontroller.v1.GetControlsRequest",
  () => [
    { no: 1, name: "controller", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 99, name: "extra", kind: "message", T: Struct },
  ],
);

/**
 * @generated from message viam.component.inputcontroller.v1.GetControlsResponse
 */
export const GetControlsResponse = /*@__PURE__*/ proto3.makeMessageType(
  "viam.component.inputcontroller.v1.GetControlsResponse",
  () => [
    { no: 1, name: "controls", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
  ],
);

/**
 * @generated from message viam.component.inputcontroller.v1.GetEventsRequest
 */
export const GetEventsRequest = /*@__PURE__*/ proto3.makeMessageType(
  "viam.component.inputcontroller.v1.GetEventsRequest",
  () => [
    { no: 1, name: "controller", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 99, name: "extra", kind: "message", T: Struct },
  ],
);

/**
 * @generated from message viam.component.inputcontroller.v1.GetEventsResponse
 */
export const GetEventsResponse = /*@__PURE__*/ proto3.makeMessageType(
  "viam.component.inputcontroller.v1.GetEventsResponse",
  () => [
    { no: 1, name: "events", kind: "message", T: Event, repeated: true },
  ],
);

/**
 * @generated from message viam.component.inputcontroller.v1.TriggerEventRequest
 */
export const TriggerEventRequest = /*@__PURE__*/ proto3.makeMessageType(
  "viam.component.inputcontroller.v1.TriggerEventRequest",
  () => [
    { no: 1, name: "controller", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "event", kind: "message", T: Event },
    { no: 99, name: "extra", kind: "message", T: Struct },
  ],
);

/**
 * @generated from message viam.component.inputcontroller.v1.TriggerEventResponse
 */
export const TriggerEventResponse = /*@__PURE__*/ proto3.makeMessageType(
  "viam.component.inputcontroller.v1.TriggerEventResponse",
  [],
);

/**
 * @generated from message viam.component.inputcontroller.v1.Event
 */
export const Event = /*@__PURE__*/ proto3.makeMessageType(
  "viam.component.inputcontroller.v1.Event",
  () => [
    { no: 1, name: "time", kind: "message", T: Timestamp },
    { no: 2, name: "event", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "control", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "value", kind: "scalar", T: 1 /* ScalarType.DOUBLE */ },
  ],
);

/**
 * @generated from message viam.component.inputcontroller.v1.StreamEventsRequest
 */
export const StreamEventsRequest = /*@__PURE__*/ proto3.makeMessageType(
  "viam.component.inputcontroller.v1.StreamEventsRequest",
  () => [
    { no: 1, name: "controller", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "events", kind: "message", T: StreamEventsRequest_Events, repeated: true },
    { no: 99, name: "extra", kind: "message", T: Struct },
  ],
);

/**
 * @generated from message viam.component.inputcontroller.v1.StreamEventsRequest.Events
 */
export const StreamEventsRequest_Events = /*@__PURE__*/ proto3.makeMessageType(
  "viam.component.inputcontroller.v1.StreamEventsRequest.Events",
  () => [
    { no: 1, name: "control", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "events", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
    { no: 3, name: "cancelled_events", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
  ],
  {localName: "StreamEventsRequest_Events"},
);

/**
 * @generated from message viam.component.inputcontroller.v1.StreamEventsResponse
 */
export const StreamEventsResponse = /*@__PURE__*/ proto3.makeMessageType(
  "viam.component.inputcontroller.v1.StreamEventsResponse",
  () => [
    { no: 1, name: "event", kind: "message", T: Event },
  ],
);

/**
 * @generated from message viam.component.inputcontroller.v1.Status
 */
export const Status = /*@__PURE__*/ proto3.makeMessageType(
  "viam.component.inputcontroller.v1.Status",
  () => [
    { no: 1, name: "events", kind: "message", T: Event, repeated: true },
  ],
);

