// Copyright 2019, OpenTelemetry Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// @generated by protoc-gen-es v1.10.0
// @generated from file opentelemetry/proto/common/v1/common.proto (package opentelemetry.proto.common.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * Represents any type of attribute value. AnyValue may contain a
 * primitive value such as a string or integer or it may contain an arbitrary nested
 * object containing arrays, key-value lists and primitives.
 *
 * @generated from message opentelemetry.proto.common.v1.AnyValue
 */
export declare class AnyValue extends Message<AnyValue> {
  /**
   * The value is one of the listed fields. It is valid for all values to be unspecified
   * in which case this AnyValue is considered to be "empty".
   *
   * @generated from oneof opentelemetry.proto.common.v1.AnyValue.value
   */
  value: {
    /**
     * @generated from field: string string_value = 1;
     */
    value: string;
    case: "stringValue";
  } | {
    /**
     * @generated from field: bool bool_value = 2;
     */
    value: boolean;
    case: "boolValue";
  } | {
    /**
     * @generated from field: int64 int_value = 3;
     */
    value: bigint;
    case: "intValue";
  } | {
    /**
     * @generated from field: double double_value = 4;
     */
    value: number;
    case: "doubleValue";
  } | {
    /**
     * @generated from field: opentelemetry.proto.common.v1.ArrayValue array_value = 5;
     */
    value: ArrayValue;
    case: "arrayValue";
  } | {
    /**
     * @generated from field: opentelemetry.proto.common.v1.KeyValueList kvlist_value = 6;
     */
    value: KeyValueList;
    case: "kvlistValue";
  } | {
    /**
     * @generated from field: bytes bytes_value = 7;
     */
    value: Uint8Array;
    case: "bytesValue";
  } | {
    /**
     * Reference to the string value in ProfilesDictionary.string_table.
     *
     * Note: This is currently used exclusively in the Profiling signal.
     * Implementers of OTLP receivers for signals other than Profiling should
     * treat the presence of this value as a non-fatal issue.
     * Log an error or warning indicating an unexpected field intended for the
     * Profiling signal and process the data as if this value were absent or
     * empty, ignoring its semantic content for the non-Profiling signal.
     *
     * Status: [Development]
     *
     * @generated from field: int32 string_value_strindex = 8;
     */
    value: number;
    case: "stringValueStrindex";
  } | { case: undefined; value?: undefined };

  constructor(data?: PartialMessage<AnyValue>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "opentelemetry.proto.common.v1.AnyValue";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): AnyValue;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): AnyValue;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): AnyValue;

  static equals(a: AnyValue | PlainMessage<AnyValue> | undefined, b: AnyValue | PlainMessage<AnyValue> | undefined): boolean;
}

/**
 * ArrayValue is a list of AnyValue messages. We need ArrayValue as a message
 * since oneof in AnyValue does not allow repeated fields.
 *
 * @generated from message opentelemetry.proto.common.v1.ArrayValue
 */
export declare class ArrayValue extends Message<ArrayValue> {
  /**
   * Array of values. The array may be empty (contain 0 elements).
   *
   * @generated from field: repeated opentelemetry.proto.common.v1.AnyValue values = 1;
   */
  values: AnyValue[];

  constructor(data?: PartialMessage<ArrayValue>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "opentelemetry.proto.common.v1.ArrayValue";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ArrayValue;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ArrayValue;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ArrayValue;

  static equals(a: ArrayValue | PlainMessage<ArrayValue> | undefined, b: ArrayValue | PlainMessage<ArrayValue> | undefined): boolean;
}

/**
 * KeyValueList is a list of KeyValue messages. We need KeyValueList as a message
 * since `oneof` in AnyValue does not allow repeated fields. Everywhere else where we need
 * a list of KeyValue messages (e.g. in Span) we use `repeated KeyValue` directly to
 * avoid unnecessary extra wrapping (which slows down the protocol). The 2 approaches
 * are semantically equivalent.
 *
 * @generated from message opentelemetry.proto.common.v1.KeyValueList
 */
export declare class KeyValueList extends Message<KeyValueList> {
  /**
   * A collection of key/value pairs of key-value pairs. The list may be empty (may
   * contain 0 elements).
   *
   * The keys MUST be unique (it is not allowed to have more than one
   * value with the same key).
   * The behavior of software that receives duplicated keys can be unpredictable.
   *
   * @generated from field: repeated opentelemetry.proto.common.v1.KeyValue values = 1;
   */
  values: KeyValue[];

  constructor(data?: PartialMessage<KeyValueList>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "opentelemetry.proto.common.v1.KeyValueList";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): KeyValueList;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): KeyValueList;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): KeyValueList;

  static equals(a: KeyValueList | PlainMessage<KeyValueList> | undefined, b: KeyValueList | PlainMessage<KeyValueList> | undefined): boolean;
}

/**
 * Represents a key-value pair that is used to store Span attributes, Link
 * attributes, etc.
 *
 * @generated from message opentelemetry.proto.common.v1.KeyValue
 */
export declare class KeyValue extends Message<KeyValue> {
  /**
   * The key name of the pair.
   * key_ref MUST NOT be set if key is used.
   *
   * @generated from field: string key = 1;
   */
  key: string;

  /**
   * The value of the pair.
   *
   * @generated from field: opentelemetry.proto.common.v1.AnyValue value = 2;
   */
  value?: AnyValue;

  /**
   * Reference to the string key in ProfilesDictionary.string_table.
   * key MUST NOT be set if key_strindex is used.
   *
   * Note: This is currently used exclusively in the Profiling signal.
   * Implementers of OTLP receivers for signals other than Profiling should
   * treat the presence of this key as a non-fatal issue.
   * Log an error or warning indicating an unexpected field intended for the
   * Profiling signal and process the data as if this value were absent or
   * empty, ignoring its semantic content for the non-Profiling signal.
   *
   * Status: [Development]
   *
   * @generated from field: int32 key_strindex = 3;
   */
  keyStrindex: number;

  constructor(data?: PartialMessage<KeyValue>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "opentelemetry.proto.common.v1.KeyValue";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): KeyValue;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): KeyValue;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): KeyValue;

  static equals(a: KeyValue | PlainMessage<KeyValue> | undefined, b: KeyValue | PlainMessage<KeyValue> | undefined): boolean;
}

/**
 * InstrumentationScope is a message representing the instrumentation scope information
 * such as the fully qualified name and version. 
 *
 * @generated from message opentelemetry.proto.common.v1.InstrumentationScope
 */
export declare class InstrumentationScope extends Message<InstrumentationScope> {
  /**
   * A name denoting the Instrumentation scope.
   * An empty instrumentation scope name means the name is unknown.
   *
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * Defines the version of the instrumentation scope.
   * An empty instrumentation scope version means the version is unknown.
   *
   * @generated from field: string version = 2;
   */
  version: string;

  /**
   * Additional attributes that describe the scope. [Optional].
   * Attribute keys MUST be unique (it is not allowed to have more than one
   * attribute with the same key).
   * The behavior of software that receives duplicated keys can be unpredictable.
   *
   * @generated from field: repeated opentelemetry.proto.common.v1.KeyValue attributes = 3;
   */
  attributes: KeyValue[];

  /**
   * The number of attributes that were discarded. Attributes
   * can be discarded because their keys are too long or because there are too many
   * attributes. If this value is 0, then no attributes were dropped.
   *
   * @generated from field: uint32 dropped_attributes_count = 4;
   */
  droppedAttributesCount: number;

  constructor(data?: PartialMessage<InstrumentationScope>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "opentelemetry.proto.common.v1.InstrumentationScope";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): InstrumentationScope;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): InstrumentationScope;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): InstrumentationScope;

  static equals(a: InstrumentationScope | PlainMessage<InstrumentationScope> | undefined, b: InstrumentationScope | PlainMessage<InstrumentationScope> | undefined): boolean;
}

/**
 * A reference to an Entity.
 * Entity represents an object of interest associated with produced telemetry: e.g spans, metrics, profiles, or logs.
 *
 * Status: [Development]
 *
 * @generated from message opentelemetry.proto.common.v1.EntityRef
 */
export declare class EntityRef extends Message<EntityRef> {
  /**
   * The Schema URL, if known. This is the identifier of the Schema that the entity data
   * is recorded in. To learn more about Schema URL see
   * https://opentelemetry.io/docs/specs/otel/schemas/#schema-url
   *
   * This schema_url applies to the data in this message and to the Resource attributes
   * referenced by id_keys and description_keys.
   * TODO: discuss if we are happy with this somewhat complicated definition of what
   * the schema_url applies to.
   *
   * This field obsoletes the schema_url field in ResourceMetrics/ResourceSpans/ResourceLogs.
   *
   * @generated from field: string schema_url = 1;
   */
  schemaUrl: string;

  /**
   * Defines the type of the entity. MUST not change during the lifetime of the entity.
   * For example: "service" or "host". This field is required and MUST not be empty
   * for valid entities.
   *
   * @generated from field: string type = 2;
   */
  type: string;

  /**
   * Attribute Keys that identify the entity.
   * MUST not change during the lifetime of the entity. The Id must contain at least one attribute.
   * These keys MUST exist in the containing {message}.attributes.
   *
   * @generated from field: repeated string id_keys = 3;
   */
  idKeys: string[];

  /**
   * Descriptive (non-identifying) attribute keys of the entity.
   * MAY change over the lifetime of the entity. MAY be empty.
   * These attribute keys are not part of entity's identity.
   * These keys MUST exist in the containing {message}.attributes.
   *
   * @generated from field: repeated string description_keys = 4;
   */
  descriptionKeys: string[];

  constructor(data?: PartialMessage<EntityRef>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "opentelemetry.proto.common.v1.EntityRef";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): EntityRef;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): EntityRef;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): EntityRef;

  static equals(a: EntityRef | PlainMessage<EntityRef> | undefined, b: EntityRef | PlainMessage<EntityRef> | undefined): boolean;
}

