// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// @generated by protoc-gen-es v1.10.0
// @generated from file google/api/field_behavior.proto (package google.api, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { FieldOptions, proto3 } from "@bufbuild/protobuf";

/**
 * An indicator of the behavior of a given field (for example, that a field
 * is required in requests, or given as output but ignored as input).
 * This **does not** change the behavior in protocol buffers itself; it only
 * denotes the behavior and may affect how API tooling handles the field.
 *
 * Note: This enum **may** receive new values in the future.
 *
 * @generated from enum google.api.FieldBehavior
 */
export const FieldBehavior = /*@__PURE__*/ proto3.makeEnum(
  "google.api.FieldBehavior",
  [
    {no: 0, name: "FIELD_BEHAVIOR_UNSPECIFIED"},
    {no: 1, name: "OPTIONAL"},
    {no: 2, name: "REQUIRED"},
    {no: 3, name: "OUTPUT_ONLY"},
    {no: 4, name: "INPUT_ONLY"},
    {no: 5, name: "IMMUTABLE"},
    {no: 6, name: "UNORDERED_LIST"},
    {no: 7, name: "NON_EMPTY_DEFAULT"},
    {no: 8, name: "IDENTIFIER"},
  ],
);

/**
 * A designation of a specific field behavior (required, output only, etc.)
 * in protobuf messages.
 *
 * Examples:
 *
 *   string name = 1 [(google.api.field_behavior) = REQUIRED];
 *   State state = 1 [(google.api.field_behavior) = OUTPUT_ONLY];
 *   google.protobuf.Duration ttl = 1
 *     [(google.api.field_behavior) = INPUT_ONLY];
 *   google.protobuf.Timestamp expire_time = 1
 *     [(google.api.field_behavior) = OUTPUT_ONLY,
 *      (google.api.field_behavior) = IMMUTABLE];
 *
 * @generated from extension: repeated google.api.FieldBehavior field_behavior = 1052 [packed = false];
 */
export const field_behavior = proto3.makeExtension(
  "google.api.field_behavior", 
  FieldOptions, 
  () => ({ no: 1052, kind: "enum", T: proto3.getEnumType(FieldBehavior), repeated: true, packed: false }),
);

