// Copyright 2016 The gRPC Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Service exported by server reflection.  A more complete description of how
// server reflection works can be found at
// https://github.com/grpc/grpc/blob/master/doc/server-reflection.md
//
// The canonical version of this proto can be found at
// https://github.com/grpc/grpc-proto/blob/master/grpc/reflection/v1/reflection.proto

// @generated by protoc-gen-es v1.10.0
// @generated from file grpc/reflection/v1/reflection.proto (package grpc.reflection.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";

/**
 * The message sent by the client when calling ServerReflectionInfo method.
 *
 * @generated from message grpc.reflection.v1.ServerReflectionRequest
 */
export const ServerReflectionRequest = /*@__PURE__*/ proto3.makeMessageType(
  "grpc.reflection.v1.ServerReflectionRequest",
  () => [
    { no: 1, name: "host", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "file_by_filename", kind: "scalar", T: 9 /* ScalarType.STRING */, oneof: "message_request" },
    { no: 4, name: "file_containing_symbol", kind: "scalar", T: 9 /* ScalarType.STRING */, oneof: "message_request" },
    { no: 5, name: "file_containing_extension", kind: "message", T: ExtensionRequest, oneof: "message_request" },
    { no: 6, name: "all_extension_numbers_of_type", kind: "scalar", T: 9 /* ScalarType.STRING */, oneof: "message_request" },
    { no: 7, name: "list_services", kind: "scalar", T: 9 /* ScalarType.STRING */, oneof: "message_request" },
  ],
);

/**
 * The type name and extension number sent by the client when requesting
 * file_containing_extension.
 *
 * @generated from message grpc.reflection.v1.ExtensionRequest
 */
export const ExtensionRequest = /*@__PURE__*/ proto3.makeMessageType(
  "grpc.reflection.v1.ExtensionRequest",
  () => [
    { no: 1, name: "containing_type", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "extension_number", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ],
);

/**
 * The message sent by the server to answer ServerReflectionInfo method.
 *
 * @generated from message grpc.reflection.v1.ServerReflectionResponse
 */
export const ServerReflectionResponse = /*@__PURE__*/ proto3.makeMessageType(
  "grpc.reflection.v1.ServerReflectionResponse",
  () => [
    { no: 1, name: "valid_host", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "original_request", kind: "message", T: ServerReflectionRequest },
    { no: 4, name: "file_descriptor_response", kind: "message", T: FileDescriptorResponse, oneof: "message_response" },
    { no: 5, name: "all_extension_numbers_response", kind: "message", T: ExtensionNumberResponse, oneof: "message_response" },
    { no: 6, name: "list_services_response", kind: "message", T: ListServiceResponse, oneof: "message_response" },
    { no: 7, name: "error_response", kind: "message", T: ErrorResponse, oneof: "message_response" },
  ],
);

/**
 * Serialized FileDescriptorProto messages sent by the server answering
 * a file_by_filename, file_containing_symbol, or file_containing_extension
 * request.
 *
 * @generated from message grpc.reflection.v1.FileDescriptorResponse
 */
export const FileDescriptorResponse = /*@__PURE__*/ proto3.makeMessageType(
  "grpc.reflection.v1.FileDescriptorResponse",
  () => [
    { no: 1, name: "file_descriptor_proto", kind: "scalar", T: 12 /* ScalarType.BYTES */, repeated: true },
  ],
);

/**
 * A list of extension numbers sent by the server answering
 * all_extension_numbers_of_type request.
 *
 * @generated from message grpc.reflection.v1.ExtensionNumberResponse
 */
export const ExtensionNumberResponse = /*@__PURE__*/ proto3.makeMessageType(
  "grpc.reflection.v1.ExtensionNumberResponse",
  () => [
    { no: 1, name: "base_type_name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "extension_number", kind: "scalar", T: 5 /* ScalarType.INT32 */, repeated: true },
  ],
);

/**
 * A list of ServiceResponse sent by the server answering list_services request.
 *
 * @generated from message grpc.reflection.v1.ListServiceResponse
 */
export const ListServiceResponse = /*@__PURE__*/ proto3.makeMessageType(
  "grpc.reflection.v1.ListServiceResponse",
  () => [
    { no: 1, name: "service", kind: "message", T: ServiceResponse, repeated: true },
  ],
);

/**
 * The information of a single service used by ListServiceResponse to answer
 * list_services request.
 *
 * @generated from message grpc.reflection.v1.ServiceResponse
 */
export const ServiceResponse = /*@__PURE__*/ proto3.makeMessageType(
  "grpc.reflection.v1.ServiceResponse",
  () => [
    { no: 1, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * The error code and error message sent by the server when an error occurs.
 *
 * @generated from message grpc.reflection.v1.ErrorResponse
 */
export const ErrorResponse = /*@__PURE__*/ proto3.makeMessageType(
  "grpc.reflection.v1.ErrorResponse",
  () => [
    { no: 1, name: "error_code", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 2, name: "error_message", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

