// @generated by protoc-gen-connect-es v1.6.1
// @generated from file component/button/v1/button.proto (package viam.component.button.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { PushRequest, PushResponse } from "./button_pb.js";
import { MethodKind } from "@bufbuild/protobuf";
import { DoCommandRequest, DoCommandResponse, GetStatusRequest, GetStatusResponse } from "../../../common/v1/common_pb.js";

/**
 * A ButtonService services buttons associated with a machine
 *
 * @generated from service viam.component.button.v1.ButtonService
 */
export declare const ButtonService: {
  readonly typeName: "viam.component.button.v1.ButtonService",
  readonly methods: {
    /**
     * Pushes a button
     *
     * @generated from rpc viam.component.button.v1.ButtonService.Push
     */
    readonly push: {
      readonly name: "Push",
      readonly I: typeof PushRequest,
      readonly O: typeof PushResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * DoCommand sends/receives arbitrary commands
     *
     * @generated from rpc viam.component.button.v1.ButtonService.DoCommand
     */
    readonly doCommand: {
      readonly name: "DoCommand",
      readonly I: typeof DoCommandRequest,
      readonly O: typeof DoCommandResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * GetStatus returns the status of the resource
     *
     * @generated from rpc viam.component.button.v1.ButtonService.GetStatus
     */
    readonly getStatus: {
      readonly name: "GetStatus",
      readonly I: typeof GetStatusRequest,
      readonly O: typeof GetStatusResponse,
      readonly kind: MethodKind.Unary,
    },
  }
};

