// @generated by protoc-gen-connect-es v1.6.1
// @generated from file app/agent/v1/agent.proto (package viam.app.agent.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { DeviceAgentConfigRequest, DeviceAgentConfigResponse } from "./agent_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service viam.app.agent.v1.AgentDeviceService
 */
export const AgentDeviceService = {
  typeName: "viam.app.agent.v1.AgentDeviceService",
  methods: {
    /**
     * DeviceAgentConfig is for retrieving config by the on-device agent.
     *
     * @generated from rpc viam.app.agent.v1.AgentDeviceService.DeviceAgentConfig
     */
    deviceAgentConfig: {
      name: "DeviceAgentConfig",
      I: DeviceAgentConfigRequest,
      O: DeviceAgentConfigResponse,
      kind: MethodKind.Unary,
    },
  }
};

