// @generated by protoc-gen-es v1.10.0
// @generated from file component/switch/v1/switch.proto (package viam.component.switch.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage, Struct } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message viam.component.switch.v1.SetPositionRequest
 */
export declare class SetPositionRequest extends Message<SetPositionRequest> {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * @generated from field: uint32 position = 2;
   */
  position: number;

  /**
   * @generated from field: google.protobuf.Struct extra = 99;
   */
  extra?: Struct;

  constructor(data?: PartialMessage<SetPositionRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "viam.component.switch.v1.SetPositionRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SetPositionRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SetPositionRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SetPositionRequest;

  static equals(a: SetPositionRequest | PlainMessage<SetPositionRequest> | undefined, b: SetPositionRequest | PlainMessage<SetPositionRequest> | undefined): boolean;
}

/**
 * @generated from message viam.component.switch.v1.SetPositionResponse
 */
export declare class SetPositionResponse extends Message<SetPositionResponse> {
  constructor(data?: PartialMessage<SetPositionResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "viam.component.switch.v1.SetPositionResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SetPositionResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SetPositionResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SetPositionResponse;

  static equals(a: SetPositionResponse | PlainMessage<SetPositionResponse> | undefined, b: SetPositionResponse | PlainMessage<SetPositionResponse> | undefined): boolean;
}

/**
 * @generated from message viam.component.switch.v1.GetPositionRequest
 */
export declare class GetPositionRequest extends Message<GetPositionRequest> {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * @generated from field: google.protobuf.Struct extra = 99;
   */
  extra?: Struct;

  constructor(data?: PartialMessage<GetPositionRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "viam.component.switch.v1.GetPositionRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetPositionRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetPositionRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetPositionRequest;

  static equals(a: GetPositionRequest | PlainMessage<GetPositionRequest> | undefined, b: GetPositionRequest | PlainMessage<GetPositionRequest> | undefined): boolean;
}

/**
 * @generated from message viam.component.switch.v1.GetPositionResponse
 */
export declare class GetPositionResponse extends Message<GetPositionResponse> {
  /**
   * @generated from field: uint32 position = 1;
   */
  position: number;

  constructor(data?: PartialMessage<GetPositionResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "viam.component.switch.v1.GetPositionResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetPositionResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetPositionResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetPositionResponse;

  static equals(a: GetPositionResponse | PlainMessage<GetPositionResponse> | undefined, b: GetPositionResponse | PlainMessage<GetPositionResponse> | undefined): boolean;
}

/**
 * @generated from message viam.component.switch.v1.GetNumberOfPositionsRequest
 */
export declare class GetNumberOfPositionsRequest extends Message<GetNumberOfPositionsRequest> {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * @generated from field: google.protobuf.Struct extra = 99;
   */
  extra?: Struct;

  constructor(data?: PartialMessage<GetNumberOfPositionsRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "viam.component.switch.v1.GetNumberOfPositionsRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetNumberOfPositionsRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetNumberOfPositionsRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetNumberOfPositionsRequest;

  static equals(a: GetNumberOfPositionsRequest | PlainMessage<GetNumberOfPositionsRequest> | undefined, b: GetNumberOfPositionsRequest | PlainMessage<GetNumberOfPositionsRequest> | undefined): boolean;
}

/**
 * @generated from message viam.component.switch.v1.GetNumberOfPositionsResponse
 */
export declare class GetNumberOfPositionsResponse extends Message<GetNumberOfPositionsResponse> {
  /**
   * @generated from field: uint32 number_of_positions = 1;
   */
  numberOfPositions: number;

  /**
   * @generated from field: repeated string labels = 2;
   */
  labels: string[];

  constructor(data?: PartialMessage<GetNumberOfPositionsResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "viam.component.switch.v1.GetNumberOfPositionsResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetNumberOfPositionsResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetNumberOfPositionsResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetNumberOfPositionsResponse;

  static equals(a: GetNumberOfPositionsResponse | PlainMessage<GetNumberOfPositionsResponse> | undefined, b: GetNumberOfPositionsResponse | PlainMessage<GetNumberOfPositionsResponse> | undefined): boolean;
}

