name: 'Setup Environment'
description: 'Setup environment for build/lint/test jobs'

runs:
  using: 'composite'
  steps:
    - name: Setup environment
      shell: bash
      run: |
        sudo apt-get update && sudo apt-get upgrade -y
        sudo apt-get install -y software-properties-common
        apt-add-repository -y 'deb https://archive.debian.org/debian bullseye-backports main'
        sudo chown -R testbot .

