// @generated by protoc-gen-connect-es v1.6.1
// @generated from file app/v1/end_user.proto (package viam.app.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { AcceptLegalRequest, AcceptLegalResponse, GetAuthApplicationRequest, GetAuthApplicationResponse, IsLegalAcceptedRequest, IsLegalAcceptedResponse, RegisterAuthApplicationRequest, RegisterAuthApplicationResponse, UpdateAuthApplicationRequest, UpdateAuthApplicationResponse } from "./end_user_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service viam.app.v1.EndUserService
 */
export declare const EndUserService: {
  readonly typeName: "viam.app.v1.EndUserService",
  readonly methods: {
    /**
     * Returns whether the specified user has accepted end user license agreements.
     * If false, the user should not be able to use the application.
     *
     * @generated from rpc viam.app.v1.EndUserService.IsLegalAccepted
     */
    readonly isLegalAccepted: {
      readonly name: "IsLegalAccepted",
      readonly I: typeof IsLegalAcceptedRequest,
      readonly O: typeof IsLegalAcceptedResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * Marks that the specified user has accepted end user license agreements.
     *
     * @generated from rpc viam.app.v1.EndUserService.AcceptLegal
     */
    readonly acceptLegal: {
      readonly name: "AcceptLegal",
      readonly I: typeof AcceptLegalRequest,
      readonly O: typeof AcceptLegalResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * Allows users to register third party auth applications using Viam linked to the indicated organization
     *
     * @generated from rpc viam.app.v1.EndUserService.RegisterAuthApplication
     * @deprecated
     */
    readonly registerAuthApplication: {
      readonly name: "RegisterAuthApplication",
      readonly I: typeof RegisterAuthApplicationRequest,
      readonly O: typeof RegisterAuthApplicationResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * Allows users to update their third party auth applications
     *
     * @generated from rpc viam.app.v1.EndUserService.UpdateAuthApplication
     * @deprecated
     */
    readonly updateAuthApplication: {
      readonly name: "UpdateAuthApplication",
      readonly I: typeof UpdateAuthApplicationRequest,
      readonly O: typeof UpdateAuthApplicationResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * Allows users to get the config for their third party auth applications
     *
     * @generated from rpc viam.app.v1.EndUserService.GetAuthApplication
     * @deprecated
     */
    readonly getAuthApplication: {
      readonly name: "GetAuthApplication",
      readonly I: typeof GetAuthApplicationRequest,
      readonly O: typeof GetAuthApplicationResponse,
      readonly kind: MethodKind.Unary,
    },
  }
};

