// @generated by protoc-gen-es v1.10.0
// @generated from file app/v1/end_user.proto (package viam.app.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message viam.app.v1.IsLegalAcceptedRequest
 */
export declare class IsLegalAcceptedRequest extends Message<IsLegalAcceptedRequest> {
  constructor(data?: PartialMessage<IsLegalAcceptedRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "viam.app.v1.IsLegalAcceptedRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): IsLegalAcceptedRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): IsLegalAcceptedRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): IsLegalAcceptedRequest;

  static equals(a: IsLegalAcceptedRequest | PlainMessage<IsLegalAcceptedRequest> | undefined, b: IsLegalAcceptedRequest | PlainMessage<IsLegalAcceptedRequest> | undefined): boolean;
}

/**
 * @generated from message viam.app.v1.IsLegalAcceptedResponse
 */
export declare class IsLegalAcceptedResponse extends Message<IsLegalAcceptedResponse> {
  /**
   * If false, the user should not be able to use the application.
   *
   * @generated from field: bool accepted_legal = 1;
   */
  acceptedLegal: boolean;

  /**
   * Whether the user has ever accepted any version of the legal terms.
   *
   * @generated from field: bool ever_accepted_legal = 2;
   */
  everAcceptedLegal: boolean;

  constructor(data?: PartialMessage<IsLegalAcceptedResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "viam.app.v1.IsLegalAcceptedResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): IsLegalAcceptedResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): IsLegalAcceptedResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): IsLegalAcceptedResponse;

  static equals(a: IsLegalAcceptedResponse | PlainMessage<IsLegalAcceptedResponse> | undefined, b: IsLegalAcceptedResponse | PlainMessage<IsLegalAcceptedResponse> | undefined): boolean;
}

/**
 * @generated from message viam.app.v1.AcceptLegalRequest
 */
export declare class AcceptLegalRequest extends Message<AcceptLegalRequest> {
  constructor(data?: PartialMessage<AcceptLegalRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "viam.app.v1.AcceptLegalRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): AcceptLegalRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): AcceptLegalRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): AcceptLegalRequest;

  static equals(a: AcceptLegalRequest | PlainMessage<AcceptLegalRequest> | undefined, b: AcceptLegalRequest | PlainMessage<AcceptLegalRequest> | undefined): boolean;
}

/**
 * @generated from message viam.app.v1.AcceptLegalResponse
 */
export declare class AcceptLegalResponse extends Message<AcceptLegalResponse> {
  constructor(data?: PartialMessage<AcceptLegalResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "viam.app.v1.AcceptLegalResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): AcceptLegalResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): AcceptLegalResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): AcceptLegalResponse;

  static equals(a: AcceptLegalResponse | PlainMessage<AcceptLegalResponse> | undefined, b: AcceptLegalResponse | PlainMessage<AcceptLegalResponse> | undefined): boolean;
}

/**
 * @generated from message viam.app.v1.RegisterAuthApplicationRequest
 * @deprecated
 */
export declare class RegisterAuthApplicationRequest extends Message<RegisterAuthApplicationRequest> {
  /**
   * @generated from field: string application_name = 1;
   */
  applicationName: string;

  /**
   * @generated from field: string org_id = 2;
   */
  orgId: string;

  /**
   * @generated from field: repeated string origin_uris = 3;
   */
  originUris: string[];

  /**
   * @generated from field: repeated string redirect_uris = 4;
   */
  redirectUris: string[];

  /**
   * @generated from field: string logout_uri = 5;
   */
  logoutUri: string;

  constructor(data?: PartialMessage<RegisterAuthApplicationRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "viam.app.v1.RegisterAuthApplicationRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RegisterAuthApplicationRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RegisterAuthApplicationRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RegisterAuthApplicationRequest;

  static equals(a: RegisterAuthApplicationRequest | PlainMessage<RegisterAuthApplicationRequest> | undefined, b: RegisterAuthApplicationRequest | PlainMessage<RegisterAuthApplicationRequest> | undefined): boolean;
}

/**
 * @generated from message viam.app.v1.RegisterAuthApplicationResponse
 * @deprecated
 */
export declare class RegisterAuthApplicationResponse extends Message<RegisterAuthApplicationResponse> {
  /**
   * @generated from field: string application_id = 1;
   */
  applicationId: string;

  /**
   * @generated from field: string application_name = 2;
   */
  applicationName: string;

  /**
   * @generated from field: string client_secret = 3;
   */
  clientSecret: string;

  constructor(data?: PartialMessage<RegisterAuthApplicationResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "viam.app.v1.RegisterAuthApplicationResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RegisterAuthApplicationResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RegisterAuthApplicationResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RegisterAuthApplicationResponse;

  static equals(a: RegisterAuthApplicationResponse | PlainMessage<RegisterAuthApplicationResponse> | undefined, b: RegisterAuthApplicationResponse | PlainMessage<RegisterAuthApplicationResponse> | undefined): boolean;
}

/**
 * @generated from message viam.app.v1.UpdateAuthApplicationRequest
 * @deprecated
 */
export declare class UpdateAuthApplicationRequest extends Message<UpdateAuthApplicationRequest> {
  /**
   * @generated from field: string org_id = 1;
   */
  orgId: string;

  /**
   * @generated from field: string application_id = 2;
   */
  applicationId: string;

  /**
   * @generated from field: string application_name = 3;
   */
  applicationName: string;

  /**
   * @generated from field: repeated string origin_uris = 4;
   */
  originUris: string[];

  /**
   * @generated from field: repeated string redirect_uris = 5;
   */
  redirectUris: string[];

  /**
   * @generated from field: string logout_uri = 6;
   */
  logoutUri: string;

  constructor(data?: PartialMessage<UpdateAuthApplicationRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "viam.app.v1.UpdateAuthApplicationRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): UpdateAuthApplicationRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): UpdateAuthApplicationRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): UpdateAuthApplicationRequest;

  static equals(a: UpdateAuthApplicationRequest | PlainMessage<UpdateAuthApplicationRequest> | undefined, b: UpdateAuthApplicationRequest | PlainMessage<UpdateAuthApplicationRequest> | undefined): boolean;
}

/**
 * @generated from message viam.app.v1.UpdateAuthApplicationResponse
 * @deprecated
 */
export declare class UpdateAuthApplicationResponse extends Message<UpdateAuthApplicationResponse> {
  /**
   * @generated from field: string application_id = 1;
   */
  applicationId: string;

  /**
   * @generated from field: string application_name = 2;
   */
  applicationName: string;

  constructor(data?: PartialMessage<UpdateAuthApplicationResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "viam.app.v1.UpdateAuthApplicationResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): UpdateAuthApplicationResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): UpdateAuthApplicationResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): UpdateAuthApplicationResponse;

  static equals(a: UpdateAuthApplicationResponse | PlainMessage<UpdateAuthApplicationResponse> | undefined, b: UpdateAuthApplicationResponse | PlainMessage<UpdateAuthApplicationResponse> | undefined): boolean;
}

/**
 * @generated from message viam.app.v1.GetAuthApplicationRequest
 * @deprecated
 */
export declare class GetAuthApplicationRequest extends Message<GetAuthApplicationRequest> {
  /**
   * @generated from field: string org_id = 1;
   */
  orgId: string;

  /**
   * @generated from field: string application_id = 2;
   */
  applicationId: string;

  constructor(data?: PartialMessage<GetAuthApplicationRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "viam.app.v1.GetAuthApplicationRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetAuthApplicationRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetAuthApplicationRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetAuthApplicationRequest;

  static equals(a: GetAuthApplicationRequest | PlainMessage<GetAuthApplicationRequest> | undefined, b: GetAuthApplicationRequest | PlainMessage<GetAuthApplicationRequest> | undefined): boolean;
}

/**
 * @generated from message viam.app.v1.GetAuthApplicationResponse
 * @deprecated
 */
export declare class GetAuthApplicationResponse extends Message<GetAuthApplicationResponse> {
  /**
   * @generated from field: string application_id = 1;
   */
  applicationId: string;

  /**
   * @generated from field: string application_name = 2;
   */
  applicationName: string;

  /**
   * @generated from field: string client_secret = 3;
   */
  clientSecret: string;

  /**
   * @generated from field: repeated string origin_uris = 4;
   */
  originUris: string[];

  /**
   * @generated from field: repeated string redirect_uris = 5;
   */
  redirectUris: string[];

  /**
   * @generated from field: string logout_uri = 6;
   */
  logoutUri: string;

  constructor(data?: PartialMessage<GetAuthApplicationResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "viam.app.v1.GetAuthApplicationResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetAuthApplicationResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetAuthApplicationResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetAuthApplicationResponse;

  static equals(a: GetAuthApplicationResponse | PlainMessage<GetAuthApplicationResponse> | undefined, b: GetAuthApplicationResponse | PlainMessage<GetAuthApplicationResponse> | undefined): boolean;
}

