// @generated by protoc-gen-connect-es v1.6.1
// @generated from file app/v1/robot.proto (package viam.app.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { CertificateRequest, CertificateResponse, ConfigRequest, ConfigResponse, LogRequest, LogResponse, NeedsRestartRequest, NeedsRestartResponse } from "./robot_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * RobotService is used by robots to retrieve configs, report logs, etc...
 *
 * @generated from service viam.app.v1.RobotService
 */
export const RobotService = {
  typeName: "viam.app.v1.RobotService",
  methods: {
    /**
     * Config requests the current robot config
     *
     * @generated from rpc viam.app.v1.RobotService.Config
     */
    config: {
      name: "Config",
      I: ConfigRequest,
      O: ConfigResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Certificate requests the current robot certificate
     *
     * @generated from rpc viam.app.v1.RobotService.Certificate
     */
    certificate: {
      name: "Certificate",
      I: CertificateRequest,
      O: CertificateResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Log insert log entries associated with the robot. Allows up to 1000 entries to be added in one request.
     *
     * @generated from rpc viam.app.v1.RobotService.Log
     */
    log: {
      name: "Log",
      I: LogRequest,
      O: LogResponse,
      kind: MethodKind.Unary,
    },
    /**
     * NeedsRestart returns if the robot should restart and the interval it should check to restart.
     *
     * @generated from rpc viam.app.v1.RobotService.NeedsRestart
     */
    needsRestart: {
      name: "NeedsRestart",
      I: NeedsRestartRequest,
      O: NeedsRestartResponse,
      kind: MethodKind.Unary,
    },
  }
};

