// @generated by protoc-gen-es v1.10.0
// @generated from file component/gripper/v1/gripper.proto (package viam.component.gripper.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage, Struct } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message viam.component.gripper.v1.OpenRequest
 */
export declare class OpenRequest extends Message<OpenRequest> {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * @generated from field: google.protobuf.Struct extra = 99;
   */
  extra?: Struct;

  constructor(data?: PartialMessage<OpenRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "viam.component.gripper.v1.OpenRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): OpenRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): OpenRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): OpenRequest;

  static equals(a: OpenRequest | PlainMessage<OpenRequest> | undefined, b: OpenRequest | PlainMessage<OpenRequest> | undefined): boolean;
}

/**
 * @generated from message viam.component.gripper.v1.OpenResponse
 */
export declare class OpenResponse extends Message<OpenResponse> {
  constructor(data?: PartialMessage<OpenResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "viam.component.gripper.v1.OpenResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): OpenResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): OpenResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): OpenResponse;

  static equals(a: OpenResponse | PlainMessage<OpenResponse> | undefined, b: OpenResponse | PlainMessage<OpenResponse> | undefined): boolean;
}

/**
 * @generated from message viam.component.gripper.v1.GrabRequest
 */
export declare class GrabRequest extends Message<GrabRequest> {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * @generated from field: google.protobuf.Struct extra = 99;
   */
  extra?: Struct;

  constructor(data?: PartialMessage<GrabRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "viam.component.gripper.v1.GrabRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GrabRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GrabRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GrabRequest;

  static equals(a: GrabRequest | PlainMessage<GrabRequest> | undefined, b: GrabRequest | PlainMessage<GrabRequest> | undefined): boolean;
}

/**
 * @generated from message viam.component.gripper.v1.GrabResponse
 */
export declare class GrabResponse extends Message<GrabResponse> {
  /**
   * @generated from field: bool success = 1;
   */
  success: boolean;

  /**
   * @generated from field: google.protobuf.Struct extra = 99;
   */
  extra?: Struct;

  constructor(data?: PartialMessage<GrabResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "viam.component.gripper.v1.GrabResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GrabResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GrabResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GrabResponse;

  static equals(a: GrabResponse | PlainMessage<GrabResponse> | undefined, b: GrabResponse | PlainMessage<GrabResponse> | undefined): boolean;
}

/**
 * @generated from message viam.component.gripper.v1.StopRequest
 */
export declare class StopRequest extends Message<StopRequest> {
  /**
   * Name of a gripper
   *
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * @generated from field: google.protobuf.Struct extra = 99;
   */
  extra?: Struct;

  constructor(data?: PartialMessage<StopRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "viam.component.gripper.v1.StopRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): StopRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): StopRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): StopRequest;

  static equals(a: StopRequest | PlainMessage<StopRequest> | undefined, b: StopRequest | PlainMessage<StopRequest> | undefined): boolean;
}

/**
 * @generated from message viam.component.gripper.v1.StopResponse
 */
export declare class StopResponse extends Message<StopResponse> {
  constructor(data?: PartialMessage<StopResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "viam.component.gripper.v1.StopResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): StopResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): StopResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): StopResponse;

  static equals(a: StopResponse | PlainMessage<StopResponse> | undefined, b: StopResponse | PlainMessage<StopResponse> | undefined): boolean;
}

/**
 * @generated from message viam.component.gripper.v1.IsMovingRequest
 */
export declare class IsMovingRequest extends Message<IsMovingRequest> {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  constructor(data?: PartialMessage<IsMovingRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "viam.component.gripper.v1.IsMovingRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): IsMovingRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): IsMovingRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): IsMovingRequest;

  static equals(a: IsMovingRequest | PlainMessage<IsMovingRequest> | undefined, b: IsMovingRequest | PlainMessage<IsMovingRequest> | undefined): boolean;
}

/**
 * @generated from message viam.component.gripper.v1.IsMovingResponse
 */
export declare class IsMovingResponse extends Message<IsMovingResponse> {
  /**
   * @generated from field: bool is_moving = 1;
   */
  isMoving: boolean;

  constructor(data?: PartialMessage<IsMovingResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "viam.component.gripper.v1.IsMovingResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): IsMovingResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): IsMovingResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): IsMovingResponse;

  static equals(a: IsMovingResponse | PlainMessage<IsMovingResponse> | undefined, b: IsMovingResponse | PlainMessage<IsMovingResponse> | undefined): boolean;
}

/**
 * @generated from message viam.component.gripper.v1.IsHoldingSomethingRequest
 */
export declare class IsHoldingSomethingRequest extends Message<IsHoldingSomethingRequest> {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * @generated from field: google.protobuf.Struct extra = 99;
   */
  extra?: Struct;

  constructor(data?: PartialMessage<IsHoldingSomethingRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "viam.component.gripper.v1.IsHoldingSomethingRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): IsHoldingSomethingRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): IsHoldingSomethingRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): IsHoldingSomethingRequest;

  static equals(a: IsHoldingSomethingRequest | PlainMessage<IsHoldingSomethingRequest> | undefined, b: IsHoldingSomethingRequest | PlainMessage<IsHoldingSomethingRequest> | undefined): boolean;
}

/**
 * @generated from message viam.component.gripper.v1.IsHoldingSomethingResponse
 */
export declare class IsHoldingSomethingResponse extends Message<IsHoldingSomethingResponse> {
  /**
   * @generated from field: bool is_holding_something = 1;
   */
  isHoldingSomething: boolean;

  /**
   * @generated from field: google.protobuf.Struct meta = 99;
   */
  meta?: Struct;

  constructor(data?: PartialMessage<IsHoldingSomethingResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "viam.component.gripper.v1.IsHoldingSomethingResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): IsHoldingSomethingResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): IsHoldingSomethingResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): IsHoldingSomethingResponse;

  static equals(a: IsHoldingSomethingResponse | PlainMessage<IsHoldingSomethingResponse> | undefined, b: IsHoldingSomethingResponse | PlainMessage<IsHoldingSomethingResponse> | undefined): boolean;
}

