// @generated by protoc-gen-connect-es v1.6.1
// @generated from file service/slam/v1/slam.proto (package viam.service.slam.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { GetInternalStateRequest, GetInternalStateResponse, GetPointCloudMapRequest, GetPointCloudMapResponse, GetPositionRequest, GetPositionResponse, GetPropertiesRequest, GetPropertiesResponse } from "./slam_pb.js";
import { MethodKind } from "@bufbuild/protobuf";
import { DoCommandRequest, DoCommandResponse, GetStatusRequest, GetStatusResponse } from "../../../common/v1/common_pb.js";

/**
 * A SlamService declares the gRPC contract for a slam service
 *
 * @generated from service viam.service.slam.v1.SLAMService
 */
export const SLAMService = {
  typeName: "viam.service.slam.v1.SLAMService",
  methods: {
    /**
     * GetPosition returns the current estimated position of the robot with
     * respect to a returned component reference.
     *
     * @generated from rpc viam.service.slam.v1.SLAMService.GetPosition
     */
    getPosition: {
      name: "GetPosition",
      I: GetPositionRequest,
      O: GetPositionResponse,
      kind: MethodKind.Unary,
    },
    /**
     * GetPointCloudMap returns the latest pointcloud map available where XY is the ground
     * plane and positive Z is up, following the Right Hand Rule.
     *
     * @generated from rpc viam.service.slam.v1.SLAMService.GetPointCloudMap
     */
    getPointCloudMap: {
      name: "GetPointCloudMap",
      I: GetPointCloudMapRequest,
      O: GetPointCloudMapResponse,
      kind: MethodKind.ServerStreaming,
    },
    /**
     * GetInternalState returns the internal map as defined by the specified slam
     * algorithm required to continue mapping/localizing.
     * This endpoint is not intended for end users.
     *
     * @generated from rpc viam.service.slam.v1.SLAMService.GetInternalState
     */
    getInternalState: {
      name: "GetInternalState",
      I: GetInternalStateRequest,
      O: GetInternalStateResponse,
      kind: MethodKind.ServerStreaming,
    },
    /**
     * GetProperties returns properties of the current slam service including mapping_mode
     * and cloud_slam, where mapping_mode is the type of mapping/localizing being performed
     * and cloud_slam is a boolean representing if this SLAM service is being run in the cloud.
     *
     * @generated from rpc viam.service.slam.v1.SLAMService.GetProperties
     */
    getProperties: {
      name: "GetProperties",
      I: GetPropertiesRequest,
      O: GetPropertiesResponse,
      kind: MethodKind.Unary,
    },
    /**
     * DoCommand sends/receives arbitrary commands.
     *
     * @generated from rpc viam.service.slam.v1.SLAMService.DoCommand
     */
    doCommand: {
      name: "DoCommand",
      I: DoCommandRequest,
      O: DoCommandResponse,
      kind: MethodKind.Unary,
    },
    /**
     * GetStatus returns the status of the resource
     *
     * @generated from rpc viam.service.slam.v1.SLAMService.GetStatus
     */
    getStatus: {
      name: "GetStatus",
      I: GetStatusRequest,
      O: GetStatusResponse,
      kind: MethodKind.Unary,
    },
  }
};

