// Copyright 2025 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// @generated by protoc-gen-es v1.10.0
// @generated from file google/iam/v1/options.proto (package google.iam.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";

/**
 * Encapsulates settings provided to GetIamPolicy.
 *
 * @generated from message google.iam.v1.GetPolicyOptions
 */
export const GetPolicyOptions = /*@__PURE__*/ proto3.makeMessageType(
  "google.iam.v1.GetPolicyOptions",
  () => [
    { no: 1, name: "requested_policy_version", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ],
);

