// @generated by protoc-gen-es v1.10.0
// @generated from file component/gantry/v1/gantry.proto (package viam.component.gantry.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage, Struct } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message viam.component.gantry.v1.GetPositionRequest
 */
export declare class GetPositionRequest extends Message<GetPositionRequest> {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * Additional arguments to the method
   *
   * @generated from field: google.protobuf.Struct extra = 99;
   */
  extra?: Struct;

  constructor(data?: PartialMessage<GetPositionRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "viam.component.gantry.v1.GetPositionRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetPositionRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetPositionRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetPositionRequest;

  static equals(a: GetPositionRequest | PlainMessage<GetPositionRequest> | undefined, b: GetPositionRequest | PlainMessage<GetPositionRequest> | undefined): boolean;
}

/**
 * @generated from message viam.component.gantry.v1.GetPositionResponse
 */
export declare class GetPositionResponse extends Message<GetPositionResponse> {
  /**
   * @generated from field: repeated double positions_mm = 1;
   */
  positionsMm: number[];

  constructor(data?: PartialMessage<GetPositionResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "viam.component.gantry.v1.GetPositionResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetPositionResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetPositionResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetPositionResponse;

  static equals(a: GetPositionResponse | PlainMessage<GetPositionResponse> | undefined, b: GetPositionResponse | PlainMessage<GetPositionResponse> | undefined): boolean;
}

/**
 * @generated from message viam.component.gantry.v1.MoveToPositionRequest
 */
export declare class MoveToPositionRequest extends Message<MoveToPositionRequest> {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * Number of millimeters to move the gantry by respective to each axis.
   *
   * @generated from field: repeated double positions_mm = 2;
   */
  positionsMm: number[];

  /**
   * Speeds to move each gantry axis must match length and order of positions_mm.
   *
   * @generated from field: repeated double speeds_mm_per_sec = 3;
   */
  speedsMmPerSec: number[];

  /**
   * Additional arguments to the method
   *
   * @generated from field: google.protobuf.Struct extra = 99;
   */
  extra?: Struct;

  constructor(data?: PartialMessage<MoveToPositionRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "viam.component.gantry.v1.MoveToPositionRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MoveToPositionRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MoveToPositionRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MoveToPositionRequest;

  static equals(a: MoveToPositionRequest | PlainMessage<MoveToPositionRequest> | undefined, b: MoveToPositionRequest | PlainMessage<MoveToPositionRequest> | undefined): boolean;
}

/**
 * @generated from message viam.component.gantry.v1.MoveToPositionResponse
 */
export declare class MoveToPositionResponse extends Message<MoveToPositionResponse> {
  constructor(data?: PartialMessage<MoveToPositionResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "viam.component.gantry.v1.MoveToPositionResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MoveToPositionResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MoveToPositionResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MoveToPositionResponse;

  static equals(a: MoveToPositionResponse | PlainMessage<MoveToPositionResponse> | undefined, b: MoveToPositionResponse | PlainMessage<MoveToPositionResponse> | undefined): boolean;
}

/**
 * @generated from message viam.component.gantry.v1.HomeRequest
 */
export declare class HomeRequest extends Message<HomeRequest> {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * Additional arguments to the method
   *
   * @generated from field: google.protobuf.Struct extra = 99;
   */
  extra?: Struct;

  constructor(data?: PartialMessage<HomeRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "viam.component.gantry.v1.HomeRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): HomeRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): HomeRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): HomeRequest;

  static equals(a: HomeRequest | PlainMessage<HomeRequest> | undefined, b: HomeRequest | PlainMessage<HomeRequest> | undefined): boolean;
}

/**
 * @generated from message viam.component.gantry.v1.HomeResponse
 */
export declare class HomeResponse extends Message<HomeResponse> {
  /**
   * A bool describing whether the gantry has completed homing
   *
   * @generated from field: bool homed = 1;
   */
  homed: boolean;

  constructor(data?: PartialMessage<HomeResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "viam.component.gantry.v1.HomeResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): HomeResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): HomeResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): HomeResponse;

  static equals(a: HomeResponse | PlainMessage<HomeResponse> | undefined, b: HomeResponse | PlainMessage<HomeResponse> | undefined): boolean;
}

/**
 * @generated from message viam.component.gantry.v1.GetLengthsRequest
 */
export declare class GetLengthsRequest extends Message<GetLengthsRequest> {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * Additional arguments to the method
   *
   * @generated from field: google.protobuf.Struct extra = 99;
   */
  extra?: Struct;

  constructor(data?: PartialMessage<GetLengthsRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "viam.component.gantry.v1.GetLengthsRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetLengthsRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetLengthsRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetLengthsRequest;

  static equals(a: GetLengthsRequest | PlainMessage<GetLengthsRequest> | undefined, b: GetLengthsRequest | PlainMessage<GetLengthsRequest> | undefined): boolean;
}

/**
 * @generated from message viam.component.gantry.v1.GetLengthsResponse
 */
export declare class GetLengthsResponse extends Message<GetLengthsResponse> {
  /**
   * @generated from field: repeated double lengths_mm = 1;
   */
  lengthsMm: number[];

  constructor(data?: PartialMessage<GetLengthsResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "viam.component.gantry.v1.GetLengthsResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetLengthsResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetLengthsResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetLengthsResponse;

  static equals(a: GetLengthsResponse | PlainMessage<GetLengthsResponse> | undefined, b: GetLengthsResponse | PlainMessage<GetLengthsResponse> | undefined): boolean;
}

/**
 * @generated from message viam.component.gantry.v1.StopRequest
 */
export declare class StopRequest extends Message<StopRequest> {
  /**
   * Name of a gantry
   *
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * Additional arguments to the method
   *
   * @generated from field: google.protobuf.Struct extra = 99;
   */
  extra?: Struct;

  constructor(data?: PartialMessage<StopRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "viam.component.gantry.v1.StopRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): StopRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): StopRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): StopRequest;

  static equals(a: StopRequest | PlainMessage<StopRequest> | undefined, b: StopRequest | PlainMessage<StopRequest> | undefined): boolean;
}

/**
 * @generated from message viam.component.gantry.v1.StopResponse
 */
export declare class StopResponse extends Message<StopResponse> {
  constructor(data?: PartialMessage<StopResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "viam.component.gantry.v1.StopResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): StopResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): StopResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): StopResponse;

  static equals(a: StopResponse | PlainMessage<StopResponse> | undefined, b: StopResponse | PlainMessage<StopResponse> | undefined): boolean;
}

/**
 * @generated from message viam.component.gantry.v1.Status
 */
export declare class Status extends Message<Status> {
  /**
   * @generated from field: repeated double positions_mm = 1;
   */
  positionsMm: number[];

  /**
   * @generated from field: repeated double lengths_mm = 2;
   */
  lengthsMm: number[];

  /**
   * @generated from field: bool is_moving = 3;
   */
  isMoving: boolean;

  constructor(data?: PartialMessage<Status>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "viam.component.gantry.v1.Status";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Status;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Status;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Status;

  static equals(a: Status | PlainMessage<Status> | undefined, b: Status | PlainMessage<Status> | undefined): boolean;
}

/**
 * @generated from message viam.component.gantry.v1.IsMovingRequest
 */
export declare class IsMovingRequest extends Message<IsMovingRequest> {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  constructor(data?: PartialMessage<IsMovingRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "viam.component.gantry.v1.IsMovingRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): IsMovingRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): IsMovingRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): IsMovingRequest;

  static equals(a: IsMovingRequest | PlainMessage<IsMovingRequest> | undefined, b: IsMovingRequest | PlainMessage<IsMovingRequest> | undefined): boolean;
}

/**
 * @generated from message viam.component.gantry.v1.IsMovingResponse
 */
export declare class IsMovingResponse extends Message<IsMovingResponse> {
  /**
   * @generated from field: bool is_moving = 1;
   */
  isMoving: boolean;

  constructor(data?: PartialMessage<IsMovingResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "viam.component.gantry.v1.IsMovingResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): IsMovingResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): IsMovingResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): IsMovingResponse;

  static equals(a: IsMovingResponse | PlainMessage<IsMovingResponse> | undefined, b: IsMovingResponse | PlainMessage<IsMovingResponse> | undefined): boolean;
}

