// @generated by protoc-gen-connect-es v1.6.1
// @generated from file component/camera/v1/camera.proto (package viam.component.camera.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { GetImagesRequest, GetImagesResponse, GetPointCloudRequest, GetPointCloudResponse, GetPropertiesRequest, GetPropertiesResponse } from "./camera_pb.js";
import { MethodKind } from "@bufbuild/protobuf";
import { DoCommandRequest, DoCommandResponse, GetGeometriesRequest, GetGeometriesResponse, GetStatusRequest, GetStatusResponse } from "../../../common/v1/common_pb.js";

/**
 * A CameraService services all cameras associated with a robot
 *
 * @generated from service viam.component.camera.v1.CameraService
 */
export declare const CameraService: {
  readonly typeName: "viam.component.camera.v1.CameraService",
  readonly methods: {
    /**
     * @generated from rpc viam.component.camera.v1.CameraService.GetImages
     */
    readonly getImages: {
      readonly name: "GetImages",
      readonly I: typeof GetImagesRequest,
      readonly O: typeof GetImagesResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * GetPointCloud returns a point cloud from a camera of the underlying robot. A specific MIME type
     * can be requested but may not necessarily be the same one returned.
     *
     * @generated from rpc viam.component.camera.v1.CameraService.GetPointCloud
     */
    readonly getPointCloud: {
      readonly name: "GetPointCloud",
      readonly I: typeof GetPointCloudRequest,
      readonly O: typeof GetPointCloudResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * GetProperties returns the camera intrinsic parameters, camera distortion parameters, and extrinsic parameters from a camera of the underlying robot, if available.
     *
     * @generated from rpc viam.component.camera.v1.CameraService.GetProperties
     */
    readonly getProperties: {
      readonly name: "GetProperties",
      readonly I: typeof GetPropertiesRequest,
      readonly O: typeof GetPropertiesResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * DoCommand sends/receives arbitrary commands
     *
     * @generated from rpc viam.component.camera.v1.CameraService.DoCommand
     */
    readonly doCommand: {
      readonly name: "DoCommand",
      readonly I: typeof DoCommandRequest,
      readonly O: typeof DoCommandResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * GetStatus returns the status of the resource
     *
     * @generated from rpc viam.component.camera.v1.CameraService.GetStatus
     */
    readonly getStatus: {
      readonly name: "GetStatus",
      readonly I: typeof GetStatusRequest,
      readonly O: typeof GetStatusResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * GetGeometries returns the geometries of the component in their current configuration
     *
     * @generated from rpc viam.component.camera.v1.CameraService.GetGeometries
     */
    readonly getGeometries: {
      readonly name: "GetGeometries",
      readonly I: typeof GetGeometriesRequest,
      readonly O: typeof GetGeometriesResponse,
      readonly kind: MethodKind.Unary,
    },
  }
};

