// @generated by protoc-gen-es v1.10.0
// @generated from file proto/rpc/webrtc/v1/signaling.proto (package proto.rpc.webrtc.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3, Timestamp } from "@bufbuild/protobuf";
import { Status } from "../../../../google/rpc/status_pb.js";

/**
 * ICECandidate represents an ICE candidate.
 * From https://github.com/pion/webrtc/blob/5f6baf73255598a7b4a7c9400bb0381acc9aa3dc/icecandidateinit.go
 *
 * @generated from message proto.rpc.webrtc.v1.ICECandidate
 */
export const ICECandidate = /*@__PURE__*/ proto3.makeMessageType(
  "proto.rpc.webrtc.v1.ICECandidate",
  () => [
    { no: 1, name: "candidate", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "sdp_mid", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 3, name: "sdpm_line_index", kind: "scalar", T: 13 /* ScalarType.UINT32 */, opt: true },
    { no: 4, name: "username_fragment", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
  ],
);

/**
 * CallRequest is the SDP offer that the controlling side is making.
 *
 * @generated from message proto.rpc.webrtc.v1.CallRequest
 */
export const CallRequest = /*@__PURE__*/ proto3.makeMessageType(
  "proto.rpc.webrtc.v1.CallRequest",
  () => [
    { no: 1, name: "sdp", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "disable_trickle", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
  ],
);

/**
 * CallResponseInitStage is the first and a one time stage that represents
 * the initial response to starting a call.
 *
 * @generated from message proto.rpc.webrtc.v1.CallResponseInitStage
 */
export const CallResponseInitStage = /*@__PURE__*/ proto3.makeMessageType(
  "proto.rpc.webrtc.v1.CallResponseInitStage",
  () => [
    { no: 1, name: "sdp", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * CallResponseUpdateStage is multiply used to trickle in ICE candidates from
 * the controlled (answering) side.
 *
 * @generated from message proto.rpc.webrtc.v1.CallResponseUpdateStage
 */
export const CallResponseUpdateStage = /*@__PURE__*/ proto3.makeMessageType(
  "proto.rpc.webrtc.v1.CallResponseUpdateStage",
  () => [
    { no: 1, name: "candidate", kind: "message", T: ICECandidate },
  ],
);

/**
 * CallResponse is the SDP answer that the controlled side responds with.
 *
 * @generated from message proto.rpc.webrtc.v1.CallResponse
 */
export const CallResponse = /*@__PURE__*/ proto3.makeMessageType(
  "proto.rpc.webrtc.v1.CallResponse",
  () => [
    { no: 1, name: "uuid", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "init", kind: "message", T: CallResponseInitStage, oneof: "stage" },
    { no: 3, name: "update", kind: "message", T: CallResponseUpdateStage, oneof: "stage" },
  ],
);

/**
 * CallUpdateRequest updates the call with additional info to the controlled side.
 *
 * @generated from message proto.rpc.webrtc.v1.CallUpdateRequest
 */
export const CallUpdateRequest = /*@__PURE__*/ proto3.makeMessageType(
  "proto.rpc.webrtc.v1.CallUpdateRequest",
  () => [
    { no: 1, name: "uuid", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "candidate", kind: "message", T: ICECandidate, oneof: "update" },
    { no: 3, name: "done", kind: "scalar", T: 8 /* ScalarType.BOOL */, oneof: "update" },
    { no: 4, name: "error", kind: "message", T: Status, oneof: "update" },
  ],
);

/**
 * CallUpdateResponse contains nothing in response to a call update.
 *
 * @generated from message proto.rpc.webrtc.v1.CallUpdateResponse
 */
export const CallUpdateResponse = /*@__PURE__*/ proto3.makeMessageType(
  "proto.rpc.webrtc.v1.CallUpdateResponse",
  [],
);

/**
 * ICEServer describes an ICE server.
 *
 * @generated from message proto.rpc.webrtc.v1.ICEServer
 */
export const ICEServer = /*@__PURE__*/ proto3.makeMessageType(
  "proto.rpc.webrtc.v1.ICEServer",
  () => [
    { no: 1, name: "urls", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
    { no: 2, name: "username", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "credential", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * WebRTCConfig represents parts of a WebRTC config.
 *
 * @generated from message proto.rpc.webrtc.v1.WebRTCConfig
 */
export const WebRTCConfig = /*@__PURE__*/ proto3.makeMessageType(
  "proto.rpc.webrtc.v1.WebRTCConfig",
  () => [
    { no: 1, name: "additional_ice_servers", kind: "message", T: ICEServer, repeated: true },
    { no: 2, name: "disable_trickle", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
  ],
);

/**
 * AnswerRequestInitStage is the first and a one time stage that represents the
 * callers initial SDP request to the controlled (answerer) side.
 *
 * @generated from message proto.rpc.webrtc.v1.AnswerRequestInitStage
 */
export const AnswerRequestInitStage = /*@__PURE__*/ proto3.makeMessageType(
  "proto.rpc.webrtc.v1.AnswerRequestInitStage",
  () => [
    { no: 1, name: "sdp", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "optional_config", kind: "message", T: WebRTCConfig },
    { no: 3, name: "deadline", kind: "message", T: Timestamp, opt: true },
  ],
);

/**
 * AnswerRequestUpdateStage is multiply used to trickle in ICE candidates to
 * the controlled (answerer) side.
 *
 * @generated from message proto.rpc.webrtc.v1.AnswerRequestUpdateStage
 */
export const AnswerRequestUpdateStage = /*@__PURE__*/ proto3.makeMessageType(
  "proto.rpc.webrtc.v1.AnswerRequestUpdateStage",
  () => [
    { no: 1, name: "candidate", kind: "message", T: ICECandidate },
  ],
);

/**
 * AnswerRequestDoneStage indicates the controller is done responding with candidates.
 *
 * @generated from message proto.rpc.webrtc.v1.AnswerRequestDoneStage
 */
export const AnswerRequestDoneStage = /*@__PURE__*/ proto3.makeMessageType(
  "proto.rpc.webrtc.v1.AnswerRequestDoneStage",
  [],
);

/**
 * AnswerRequestErrorStage indicates the exchange has failed with an error.
 *
 * @generated from message proto.rpc.webrtc.v1.AnswerRequestErrorStage
 */
export const AnswerRequestErrorStage = /*@__PURE__*/ proto3.makeMessageType(
  "proto.rpc.webrtc.v1.AnswerRequestErrorStage",
  () => [
    { no: 1, name: "status", kind: "message", T: Status },
  ],
);

/**
 * AnswerRequestHeartbeatStage is sent periodically to verify liveness of answerer.
 *
 * @generated from message proto.rpc.webrtc.v1.AnswerRequestHeartbeatStage
 */
export const AnswerRequestHeartbeatStage = /*@__PURE__*/ proto3.makeMessageType(
  "proto.rpc.webrtc.v1.AnswerRequestHeartbeatStage",
  [],
);

/**
 * AnswerRequest is the SDP offer that the controlling side is making via the answering
 * stream.
 *
 * @generated from message proto.rpc.webrtc.v1.AnswerRequest
 */
export const AnswerRequest = /*@__PURE__*/ proto3.makeMessageType(
  "proto.rpc.webrtc.v1.AnswerRequest",
  () => [
    { no: 1, name: "uuid", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "init", kind: "message", T: AnswerRequestInitStage, oneof: "stage" },
    { no: 3, name: "update", kind: "message", T: AnswerRequestUpdateStage, oneof: "stage" },
    { no: 4, name: "done", kind: "message", T: AnswerRequestDoneStage, oneof: "stage" },
    { no: 5, name: "error", kind: "message", T: AnswerRequestErrorStage, oneof: "stage" },
    { no: 6, name: "heartbeat", kind: "message", T: AnswerRequestHeartbeatStage, oneof: "stage" },
  ],
);

/**
 * AnswerResponseInitStage is the first and a one time stage that represents the
 * answerers initial SDP response to the controlling side.
 *
 * @generated from message proto.rpc.webrtc.v1.AnswerResponseInitStage
 */
export const AnswerResponseInitStage = /*@__PURE__*/ proto3.makeMessageType(
  "proto.rpc.webrtc.v1.AnswerResponseInitStage",
  () => [
    { no: 1, name: "sdp", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * AnswerResponseUpdateStage is multiply used to trickle in ICE candidates to
 * the controlling side.
 *
 * @generated from message proto.rpc.webrtc.v1.AnswerResponseUpdateStage
 */
export const AnswerResponseUpdateStage = /*@__PURE__*/ proto3.makeMessageType(
  "proto.rpc.webrtc.v1.AnswerResponseUpdateStage",
  () => [
    { no: 1, name: "candidate", kind: "message", T: ICECandidate },
  ],
);

/**
 * AnswerResponseDoneStage indicates the answerer is done responding with candidates.
 *
 * @generated from message proto.rpc.webrtc.v1.AnswerResponseDoneStage
 */
export const AnswerResponseDoneStage = /*@__PURE__*/ proto3.makeMessageType(
  "proto.rpc.webrtc.v1.AnswerResponseDoneStage",
  [],
);

/**
 * AnswerResponseErrorStage indicates the exchange has failed with an error.
 *
 * @generated from message proto.rpc.webrtc.v1.AnswerResponseErrorStage
 */
export const AnswerResponseErrorStage = /*@__PURE__*/ proto3.makeMessageType(
  "proto.rpc.webrtc.v1.AnswerResponseErrorStage",
  () => [
    { no: 1, name: "status", kind: "message", T: Status },
  ],
);

/**
 * AnswerResponse is the SDP answer that an answerer responds with.
 *
 * @generated from message proto.rpc.webrtc.v1.AnswerResponse
 */
export const AnswerResponse = /*@__PURE__*/ proto3.makeMessageType(
  "proto.rpc.webrtc.v1.AnswerResponse",
  () => [
    { no: 1, name: "uuid", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "init", kind: "message", T: AnswerResponseInitStage, oneof: "stage" },
    { no: 3, name: "update", kind: "message", T: AnswerResponseUpdateStage, oneof: "stage" },
    { no: 4, name: "done", kind: "message", T: AnswerResponseDoneStage, oneof: "stage" },
    { no: 5, name: "error", kind: "message", T: AnswerResponseErrorStage, oneof: "stage" },
  ],
);

/**
 * OptionalWebRTCConfigRequest is the request for getting an optional WebRTC config
 * to use for the peer connection.
 *
 * @generated from message proto.rpc.webrtc.v1.OptionalWebRTCConfigRequest
 */
export const OptionalWebRTCConfigRequest = /*@__PURE__*/ proto3.makeMessageType(
  "proto.rpc.webrtc.v1.OptionalWebRTCConfigRequest",
  [],
);

/**
 * OptionalWebRTCConfigResponse contains the optional WebRTC config
 * to use for the peer connection.
 *
 * @generated from message proto.rpc.webrtc.v1.OptionalWebRTCConfigResponse
 */
export const OptionalWebRTCConfigResponse = /*@__PURE__*/ proto3.makeMessageType(
  "proto.rpc.webrtc.v1.OptionalWebRTCConfigResponse",
  () => [
    { no: 1, name: "config", kind: "message", T: WebRTCConfig },
  ],
);

