// @generated by protoc-gen-connect-es v1.6.1
// @generated from file component/posetracker/v1/pose_tracker.proto (package viam.component.posetracker.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { GetPosesRequest, GetPosesResponse } from "./pose_tracker_pb.js";
import { MethodKind } from "@bufbuild/protobuf";
import { DoCommandRequest, DoCommandResponse, GetGeometriesRequest, GetGeometriesResponse, GetStatusRequest, GetStatusResponse } from "../../../common/v1/common_pb.js";

/**
 * A PoseTrackerService maintains all pose trackers associated with a robot
 *
 * @generated from service viam.component.posetracker.v1.PoseTrackerService
 */
export declare const PoseTrackerService: {
  readonly typeName: "viam.component.posetracker.v1.PoseTrackerService",
  readonly methods: {
    /**
     * GetPoses returns the current pose of each body tracked by the pose tracker
     *
     * @generated from rpc viam.component.posetracker.v1.PoseTrackerService.GetPoses
     */
    readonly getPoses: {
      readonly name: "GetPoses",
      readonly I: typeof GetPosesRequest,
      readonly O: typeof GetPosesResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * DoCommand sends/receives arbitrary commands
     *
     * @generated from rpc viam.component.posetracker.v1.PoseTrackerService.DoCommand
     */
    readonly doCommand: {
      readonly name: "DoCommand",
      readonly I: typeof DoCommandRequest,
      readonly O: typeof DoCommandResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * GetStatus returns the status of the resource
     *
     * @generated from rpc viam.component.posetracker.v1.PoseTrackerService.GetStatus
     */
    readonly getStatus: {
      readonly name: "GetStatus",
      readonly I: typeof GetStatusRequest,
      readonly O: typeof GetStatusResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * GetGeometries returns the geometries of the component in their current configuration
     *
     * @generated from rpc viam.component.posetracker.v1.PoseTrackerService.GetGeometries
     */
    readonly getGeometries: {
      readonly name: "GetGeometries",
      readonly I: typeof GetGeometriesRequest,
      readonly O: typeof GetGeometriesResponse,
      readonly kind: MethodKind.Unary,
    },
  }
};

