// @generated by protoc-gen-es v1.10.0
// @generated from file component/posetracker/v1/pose_tracker.proto (package viam.component.posetracker.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage, Struct } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";
import type { PoseInFrame } from "../../../common/v1/common_pb.js";

/**
 * @generated from message viam.component.posetracker.v1.GetPosesRequest
 */
export declare class GetPosesRequest extends Message<GetPosesRequest> {
  /**
   * Name of the pose tracker
   *
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * Names of the bodies whose poses are being requested. In the event
   * this parameter is not supplied or is an empty list, all available
   * poses are returned
   *
   * @generated from field: repeated string body_names = 2;
   */
  bodyNames: string[];

  /**
   * Additional arguments to the method
   *
   * @generated from field: google.protobuf.Struct extra = 99;
   */
  extra?: Struct;

  constructor(data?: PartialMessage<GetPosesRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "viam.component.posetracker.v1.GetPosesRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetPosesRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetPosesRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetPosesRequest;

  static equals(a: GetPosesRequest | PlainMessage<GetPosesRequest> | undefined, b: GetPosesRequest | PlainMessage<GetPosesRequest> | undefined): boolean;
}

/**
 * @generated from message viam.component.posetracker.v1.GetPosesResponse
 */
export declare class GetPosesResponse extends Message<GetPosesResponse> {
  /**
   * Mapping of each body name to the pose representing the center of the body.
   *
   * @generated from field: map<string, viam.common.v1.PoseInFrame> body_poses = 1;
   */
  bodyPoses: { [key: string]: PoseInFrame };

  constructor(data?: PartialMessage<GetPosesResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "viam.component.posetracker.v1.GetPosesResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetPosesResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetPosesResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetPosesResponse;

  static equals(a: GetPosesResponse | PlainMessage<GetPosesResponse> | undefined, b: GetPosesResponse | PlainMessage<GetPosesResponse> | undefined): boolean;
}

