// @generated by protoc-gen-connect-es v1.6.1
// @generated from file component/sensor/v1/sensor.proto (package viam.component.sensor.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { DoCommandRequest, DoCommandResponse, GetGeometriesRequest, GetGeometriesResponse, GetReadingsRequest, GetReadingsResponse, GetStatusRequest, GetStatusResponse } from "../../../common/v1/common_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * SensorService services all generic sensors associated with a robot
 *
 * @generated from service viam.component.sensor.v1.SensorService
 */
export declare const SensorService: {
  readonly typeName: "viam.component.sensor.v1.SensorService",
  readonly methods: {
    /**
     * GetReadings returns the readings of a sensor of the underlying robot.
     *
     * @generated from rpc viam.component.sensor.v1.SensorService.GetReadings
     */
    readonly getReadings: {
      readonly name: "GetReadings",
      readonly I: typeof GetReadingsRequest,
      readonly O: typeof GetReadingsResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * DoCommand sends/receives arbitrary commands
     *
     * @generated from rpc viam.component.sensor.v1.SensorService.DoCommand
     */
    readonly doCommand: {
      readonly name: "DoCommand",
      readonly I: typeof DoCommandRequest,
      readonly O: typeof DoCommandResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * GetStatus returns the status of the resource
     *
     * @generated from rpc viam.component.sensor.v1.SensorService.GetStatus
     */
    readonly getStatus: {
      readonly name: "GetStatus",
      readonly I: typeof GetStatusRequest,
      readonly O: typeof GetStatusResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * GetGeometries returns the geometries of the component in their current configuration
     *
     * @generated from rpc viam.component.sensor.v1.SensorService.GetGeometries
     */
    readonly getGeometries: {
      readonly name: "GetGeometries",
      readonly I: typeof GetGeometriesRequest,
      readonly O: typeof GetGeometriesResponse,
      readonly kind: MethodKind.Unary,
    },
  }
};

