name: 'Prepare Workflow'
description: 'Setup environment, cache and install dependencies, and optionally download build artifacts'

inputs:
  download_build_artifacts:
    description: 'Whether to download full build artifacts (for test-e2e only)'
    required: false
    default: 'false'

runs:
  using: 'composite'
  steps:
    - name: Setup environment
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y software-properties-common jq
        apt-add-repository -y 'deb https://archive.debian.org/debian bullseye-backports main'
        sudo chown -R testbot .

    - name: Read Node.js version from package.json
      id: node-version
      shell: bash
      run: |
        NODE_VERSION=$(jq -r '.engines.node' package.json | sed 's/[^0-9]//g')
        echo "version=$NODE_VERSION" >> $GITHUB_OUTPUT
        echo "Using Node.js version: $NODE_VERSION"

    - name: Setup Node.js
      uses: actions/setup-node@v6
      with:
        node-version: ${{ steps.node-version.outputs.version }}
        cache: 'npm'

    - name: Restore node_modules cache
      uses: actions/cache/restore@v4
      id: cache-node-modules
      with:
        path: node_modules
        key: node-modules-${{ runner.os }}-${{ steps.node-version.outputs.version }}-${{ hashFiles('package-lock.json') }}
        restore-keys: |
          node-modules-${{ runner.os }}-${{ steps.node-version.outputs.version }}-
          node-modules-${{ runner.os }}-

    - name: Install npm dependencies
      if: steps.cache-node-modules.outputs.cache-hit != 'true'
      shell: bash
      run: sudo -u testbot bash -lc 'npm ci --audit=false'

    - name: Save node_modules cache
      if: steps.cache-node-modules.outputs.cache-hit != 'true'
      uses: actions/cache/save@v4
      with:
        path: node_modules
        key: node-modules-${{ runner.os }}-${{ steps.node-version.outputs.version }}-${{ hashFiles('package-lock.json') }}

    - name: Generate api-version.ts
      shell: bash
      run: sudo -u testbot bash -lc 'node ./scripts/write-versions.js'
      
    - name: Download build artifacts
      if: inputs.download_build_artifacts == 'true'
      uses: actions/download-artifact@v4
      with:
        name: build-artifacts
        path: .

    - name: Restore build-buf cache
      if: inputs.download_build_artifacts != 'true'
      uses: actions/cache/restore@v4
      id: cache-build-buf
      with:
        path: src/gen
        key: build-buf-${{ runner.os }}-${{ hashFiles('api_version.lock', 'buf.gen.yaml') }}
        restore-keys: |
          build-buf-${{ runner.os }}-${{ hashFiles('api_version.lock') }}-
          build-buf-${{ runner.os }}-

    - name: Generate build-buf if not cached
      if: inputs.download_build_artifacts != 'true' && steps.cache-build-buf.outputs.cache-hit != 'true'
      shell: bash
      run: sudo -u testbot bash -lc 'make build-buf-ci'

    - name: Save build-buf cache
      if: inputs.download_build_artifacts != 'true' && steps.cache-build-buf.outputs.cache-hit != 'true'
      uses: actions/cache/save@v4
      with:
        path: src/gen
        key: build-buf-${{ runner.os }}-${{ hashFiles('api_version.lock', 'buf.gen.yaml') }}

