name: 'Prepare Workflow'
description: 'Setup environment, cache and install dependencies, and optionally download build artifacts'

inputs:
  e2e:
    description: 'Whether to prepare for e2e tests'
    required: false
    default: 'false'

runs:
  using: 'composite'
  steps:
    - name: Setup environment
      shell: bash
      run: |
        sudo chown -R testbot .
        sudo mkdir -p /home/testbot/.cache/buf
        sudo chown -R testbot:testbot /home/testbot/.cache
        sudo mkdir -p /github/home/.npm
        sudo chown -R testbot:testbot /github/home/.npm

    - name: Setup Node.js
      uses: actions/setup-node@v6
      with:
        node-version: '22'
        cache: 'npm'

    - name: Restore node_modules cache
      uses: actions/cache/restore@v4
      id: cache-node-modules
      with:
        path: node_modules
        key: node-modules-${{ runner.os }}-${{ hashFiles('package-lock.json') }}
        restore-keys: |
          node-modules-${{ runner.os }}-

    - name: Install npm dependencies
      if: steps.cache-node-modules.outputs.cache-hit != 'true'
      shell: bash
      run: sudo -E -u testbot bash -lc 'npm ci --audit=false'

    - name: Save node_modules cache
      if: steps.cache-node-modules.outputs.cache-hit != 'true'
      uses: actions/cache/save@v4
      with:
        path: node_modules
        key: node-modules-${{ runner.os }}-${{ hashFiles('package-lock.json') }}

    - name: Generate api-version.ts
      shell: bash
      run: sudo -E -u testbot bash -lc 'node ./scripts/write-versions.js'

    - name: Download build artifacts
      if: inputs.e2e == 'true'
      uses: actions/download-artifact@v4
      with:
        name: build-artifacts
        path: .

    - name: Restore build-buf cache
      if: inputs.e2e != 'true'
      uses: actions/cache/restore@v4
      id: cache-build-buf
      with:
        path: src/gen
        key: build-buf-${{ runner.os }}-${{ hashFiles('api_version.lock', 'buf.gen.yaml') }}
        restore-keys: |
          build-buf-${{ runner.os }}-${{ hashFiles('api_version.lock') }}-
          build-buf-${{ runner.os }}-

    - name: Generate build-buf if not cached
      if: inputs.e2e != 'true' && steps.cache-build-buf.outputs.cache-hit != 'true'
      shell: bash
      run: sudo -E -u testbot bash -lc 'make build-buf-ci'

    - name: Save build-buf cache
      if: inputs.e2e != 'true' && steps.cache-build-buf.outputs.cache-hit != 'true'
      uses: actions/cache/save@v4
      with:
        path: src/gen
        key: build-buf-${{ runner.os }}-${{ hashFiles('api_version.lock', 'buf.gen.yaml') }}

    - name: Read Playwright version from package.json
      if: inputs.e2e == 'true'
      id: playwright-version
      shell: bash
      run: |
        PLAYWRIGHT_VERSION=$(jq -r '.devDependencies."@playwright/test"' package.json)
        echo "version=$PLAYWRIGHT_VERSION" >> $GITHUB_OUTPUT
        echo "Using Playwright version: $PLAYWRIGHT_VERSION"

    - name: Restore Playwright browsers cache
      if: inputs.e2e == 'true'
      uses: actions/cache/restore@v4
      id: cache-playwright
      with:
        path: /home/testbot/.cache/ms-playwright
        key: playwright-${{ runner.os }}-${{ steps.playwright-version.outputs.version }}
        restore-keys: |
          playwright-${{ runner.os }}-

    - name: Install Playwright browsers and dependencies
      if: inputs.e2e == 'true'
      shell: bash
      run: |
        sudo -E -u testbot bash -lc 'npx playwright install --with-deps'

    - name: Save Playwright browsers cache
      if: inputs.e2e == 'true' && steps.cache-playwright.outputs.cache-hit != 'true'
      uses: actions/cache/save@v4
      with:
        path: /home/testbot/.cache/ms-playwright
        key: playwright-${{ runner.os }}-${{ steps.playwright-version.outputs.version }}
