// @generated by protoc-gen-es v1.10.0
// @generated from file component/testecho/v1/testecho.proto (package viam.component.testecho.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message viam.component.testecho.v1.EchoRequest
 */
export const EchoRequest = /*@__PURE__*/ proto3.makeMessageType(
  "viam.component.testecho.v1.EchoRequest",
  () => [
    { no: 1, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "message", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message viam.component.testecho.v1.EchoResponse
 */
export const EchoResponse = /*@__PURE__*/ proto3.makeMessageType(
  "viam.component.testecho.v1.EchoResponse",
  () => [
    { no: 1, name: "message", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message viam.component.testecho.v1.EchoMultipleRequest
 */
export const EchoMultipleRequest = /*@__PURE__*/ proto3.makeMessageType(
  "viam.component.testecho.v1.EchoMultipleRequest",
  () => [
    { no: 1, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "message", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message viam.component.testecho.v1.EchoMultipleResponse
 */
export const EchoMultipleResponse = /*@__PURE__*/ proto3.makeMessageType(
  "viam.component.testecho.v1.EchoMultipleResponse",
  () => [
    { no: 1, name: "message", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message viam.component.testecho.v1.EchoBiDiRequest
 */
export const EchoBiDiRequest = /*@__PURE__*/ proto3.makeMessageType(
  "viam.component.testecho.v1.EchoBiDiRequest",
  () => [
    { no: 1, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "message", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message viam.component.testecho.v1.EchoBiDiResponse
 */
export const EchoBiDiResponse = /*@__PURE__*/ proto3.makeMessageType(
  "viam.component.testecho.v1.EchoBiDiResponse",
  () => [
    { no: 1, name: "message", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message viam.component.testecho.v1.StopRequest
 */
export const StopRequest = /*@__PURE__*/ proto3.makeMessageType(
  "viam.component.testecho.v1.StopRequest",
  () => [
    { no: 1, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message viam.component.testecho.v1.StopResponse
 */
export const StopResponse = /*@__PURE__*/ proto3.makeMessageType(
  "viam.component.testecho.v1.StopResponse",
  [],
);

