export { version } from '../package.json';

// Wrappers

/**
 * Raw Protobuf interfaces generated by
 * https://github.com/improbable-eng/grpc-web for a Robot.
 *
 * @deprecated Use {@link RobotClient} instead.
 * @group Raw Protobufs
 */
export { default as robotApi } from './gen/robot/v1/robot_pb';
export {
  type Robot,
  type DialDirectConf,
  type DialWebRTCConf,
  RobotClient,
  createRobotClient,
} from './robot';
/** @deprecated Use {@link RobotClient} instead. */
export { RobotClient as Client } from './robot';

/**
 * Raw Protobuf interfaces generated by
 * https://github.com/improbable-eng/grpc-web for an Arm component.
 *
 * @deprecated Use {@link ArmClient} instead.
 * @group Raw Protobufs
 */
export { default as armApi } from './gen/component/arm/v1/arm_pb';
export { type Arm, ArmClient } from './components/arm';

/**
 * Raw Protobuf interfaces generated by
 * https://github.com/improbable-eng/grpc-web for a Base component.
 *
 * @deprecated Use {@link BaseClient} instead.
 * @group Raw Protobufs
 */
export { default as baseApi } from './gen/component/base/v1/base_pb';
export { type Base, BaseClient } from './components/base';

/**
 * Raw Protobuf interfaces generated by
 * https://github.com/improbable-eng/grpc-web for a Board component.
 *
 * @deprecated Use {@link BoardClient} instead.
 * @group Raw Protobufs
 */
export { default as boardApi } from './gen/component/board/v1/board_pb';
export { type Board, BoardClient } from './components/board';

/**
 * Raw Protobuf interfaces generated by
 * https://github.com/improbable-eng/grpc-web for a Camera component.
 *
 * @deprecated Use {@link CameraClient} instead.
 * @group Raw Protobufs
 */
export { default as cameraApi } from './gen/component/camera/v1/camera_pb';
export { type Camera, CameraClient } from './components/camera';

/**
 * Raw Protobuf interfaces generated by
 * https://github.com/improbable-eng/grpc-web for a Motor component.
 *
 * @deprecated Use {@link MotorClient} instead.
 * @group Raw Protobufs
 */
export { default as motorApi } from './gen/component/motor/v1/motor_pb';
export { type Motor, MotorClient } from './components/motor';

/**
 * Raw Protobuf interfaces generated by
 * https://github.com/improbable-eng/grpc-web for a MovementSensor component.
 *
 * @deprecated Use {@link MovementSensorClient} instead.
 * @group Raw Protobufs
 */
export { default as movementsensorApi } from './gen/component/movementsensor/v1/movementsensor_pb';
export {
  type MovementSensor,
  MovementSensorClient,
} from './components/movementsensor';

/**
 * Raw Protobuf interfaces generated by
 * https://github.com/improbable-eng/grpc-web for a Sensor component.
 *
 * @deprecated Use {@link SensorClient} instead.
 * @group Raw Protobufs
 */
export { default as sensorApi } from './gen/component/sensor/v1/sensor_pb';
export { type Sensor, SensorClient } from './components/sensor';

/**
 * Raw Protobuf interfaces generated by
 * https://github.com/improbable-eng/grpc-web for a Stream.
 *
 * @deprecated Use {@link StreamClient} instead.
 * @group Raw Protobufs
 */
export { default as streamApi } from './gen/proto/stream/v1/stream_pb';
export { type Stream, StreamClient } from './extra/stream';

/** @group Raw Protobufs */
export { default as commonApi } from './gen/common/v1/common_pb';

/**
 * Raw Protobuf interfaces generated by
 * https://github.com/improbable-eng/grpc-web for a Gantry component.
 *
 * @example
 *
 * ```ts
 * import { grpc } from '@improbable-eng/grpc-web';
 *
 * const client = {}; // replace with a connected robot client
 *
 * const request = new gantryApi.GetLengthsRequest();
 * request.setName('my gantry');
 *
 * client.gantryService.getLengths(
 *   request,
 *   new grpc.Metadata(),
 *   (error, response) => {
 *     // do something with error or response
 *   }
 * );
 * ```
 *
 * @group Raw Protobufs
 */
export { default as gantryApi } from './gen/component/gantry/v1/gantry_pb';

/** @group Raw Protobufs */
export { default as genericApi } from './gen/component/generic/v1/generic_pb';

/** @group Raw Protobufs */
export { default as gripperApi } from './gen/component/gripper/v1/gripper_pb';

/** @group Raw Protobufs */
export { default as inputControllerApi } from './gen/component/inputcontroller/v1/input_controller_pb';

/** @group Raw Protobufs */
export { default as motionApi } from './gen/service/motion/v1/motion_pb';

/** @group Raw Protobufs */
export { default as navigationApi } from './gen/service/navigation/v1/navigation_pb';

/**
 * Raw Protobuf interfaces generated by
 * https://github.com/improbable-eng/grpc-web for a Servo component.
 *
 * @example
 *
 * ```ts
 * import { grpc } from '@improbable-eng/grpc-web';
 *
 * const client = {}; // replace with a connected robot client
 *
 * const request = new servoApi.GetPositionRequest();
 * request.setName('my servo');
 *
 * client.servoService.getPosition(
 *   request,
 *   new grpc.Metadata(),
 *   (error, response) => {
 *     // do something with error or response
 *   }
 * );
 * ```
 *
 * @alpha
 * @group Raw Protobufs
 */
export { default as servoApi } from './gen/component/servo/v1/servo_pb';

/**
 * Raw Protobuf interfaces generated by
 * https://github.com/improbable-eng/grpc-web for the Slam service.
 *
 * @example
 *
 * ```ts
 * import { grpc } from '@improbable-eng/grpc-web';
 *
 * const client = {}; // replace with a connected robot client
 *
 * const request = new slamApi.GetPositionRequest();
 * request.setName('my slam');
 *
 * client.slamService.getPosition(
 *   request,
 *   new grpc.Metadata(),
 *   (error, response) => {
 *     // do something with error or response
 *   }
 * );
 * ```
 *
 * @alpha
 * @group Raw Protobufs
 */
export { default as slamApi } from './gen/service/slam/v1/slam_pb';

/** @group Raw Protobufs */
export { default as visionApi } from './gen/service/vision/v1/vision_pb';

// It doesn't matter which ServiceError we export really.
/** @group Raw Protobufs */
export type {
  ResponseStream,
  ServiceError,
} from './gen/robot/v1/robot_pb_service';
