// @generated by protoc-gen-connect-es v1.6.1
// @generated from file service/discovery/v1/discovery.proto (package viam.service.discovery.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { DiscoverResourcesRequest, DiscoverResourcesResponse } from "./discovery_pb.js";
import { MethodKind } from "@bufbuild/protobuf";
import { DoCommandRequest, DoCommandResponse, GetStatusRequest, GetStatusResponse } from "../../../common/v1/common_pb.js";

/**
 * @generated from service viam.service.discovery.v1.DiscoveryService
 */
export declare const DiscoveryService: {
  readonly typeName: "viam.service.discovery.v1.DiscoveryService",
  readonly methods: {
    /**
     * DiscoverResources returns the list of all discovered viam resources connected to the viam-server machine.
     *
     * @generated from rpc viam.service.discovery.v1.DiscoveryService.DiscoverResources
     */
    readonly discoverResources: {
      readonly name: "DiscoverResources",
      readonly I: typeof DiscoverResourcesRequest,
      readonly O: typeof DiscoverResourcesResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * DoCommand sends/receives arbitrary commands
     *
     * @generated from rpc viam.service.discovery.v1.DiscoveryService.DoCommand
     */
    readonly doCommand: {
      readonly name: "DoCommand",
      readonly I: typeof DoCommandRequest,
      readonly O: typeof DoCommandResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * GetStatus returns the status of the resource
     *
     * @generated from rpc viam.service.discovery.v1.DiscoveryService.GetStatus
     */
    readonly getStatus: {
      readonly name: "GetStatus",
      readonly I: typeof GetStatusRequest,
      readonly O: typeof GetStatusResponse,
      readonly kind: MethodKind.Unary,
    },
  }
};

