name: 'Prepare Job'
description: 'Setup environment, cache and install dependencies, and optionally download build artifacts'

inputs:
  node_version:
    description: 'Node.js version to use'
    required: false
    default: '20'
  download_build_artifacts:
    description: 'Whether to download full build artifacts (for test-e2e only)'
    required: false
    default: 'false'

runs:
  using: 'composite'
  steps:
    - name: Setup environment
      uses: viamrobotics/viam-typescript-sdk/.github/actions/setup-environment@main

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node_version }}

    - name: Restore npm cache
      uses: actions/cache/restore@v4
      id: cache-npm
      with:
        path: node_modules
        key: ${{ runner.os }}-node-${{ inputs.node_version }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-${{ inputs.node_version }}-
          ${{ runner.os }}-node-

    - name: Install npm dependencies
      if: steps.cache-npm.outputs.cache-hit != 'true'
      shell: bash
      run: sudo -u testbot bash -lc 'npm ci --audit=false'

    - name: Save npm cache
      if: steps.cache-npm.outputs.cache-hit != 'true'
      uses: actions/cache/save@v4
      with:
        path: node_modules
        key: ${{ runner.os }}-node-${{ inputs.node_version }}-${{ hashFiles('**/package-lock.json') }}

    - name: Download build artifacts
      if: inputs.download_build_artifacts == 'true'
      uses: actions/download-artifact@v4
      with:
        name: build-artifacts
        path: .

    - name: Restore build-buf cache
      if: inputs.download_build_artifacts != 'true'
      uses: actions/cache/restore@v4
      id: cache-build-buf
      with:
        path: src/gen
        key: build-buf-${{ runner.os }}-${{ hashFiles('api_version.lock', 'buf.gen.yaml') }}
        restore-keys: |
          build-buf-${{ runner.os }}-${{ hashFiles('api_version.lock') }}-
          build-buf-${{ runner.os }}-

    - name: Generate build-buf if not cached
      if: inputs.download_build_artifacts != 'true' && steps.cache-build-buf.outputs.cache-hit != 'true'
      shell: bash
      run: sudo -u testbot bash -lc 'make build-buf-ci'

    - name: Save build-buf cache
      if: inputs.download_build_artifacts != 'true' && steps.cache-build-buf.outputs.cache-hit != 'true'
      uses: actions/cache/save@v4
      with:
        path: src/gen
        key: build-buf-${{ runner.os }}-${{ hashFiles('api_version.lock', 'buf.gen.yaml') }}

