// @generated by protoc-gen-es v1.10.0
// @generated from file service/motion/v1/motion.proto (package viam.service.motion.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3, Struct, Timestamp } from "@bufbuild/protobuf";
import { GeoGeometry, Geometry, GeoPoint, Pose, PoseInFrame, ResourceName, Transform, WorldState } from "../../../common/v1/common_pb.js";

/**
 * The states that a plan can be in.
 * InProgress if the plan is executing.
 * Stopped if the plan was stopped.
 * Suceeded if the robot reached its destination successfully.
 * Failed if the robot did not reach its destination.
 *
 * @generated from enum viam.service.motion.v1.PlanState
 */
export const PlanState = /*@__PURE__*/ proto3.makeEnum(
  "viam.service.motion.v1.PlanState",
  [
    {no: 0, name: "PLAN_STATE_UNSPECIFIED", localName: "UNSPECIFIED"},
    {no: 1, name: "PLAN_STATE_IN_PROGRESS", localName: "IN_PROGRESS"},
    {no: 2, name: "PLAN_STATE_STOPPED", localName: "STOPPED"},
    {no: 3, name: "PLAN_STATE_SUCCEEDED", localName: "SUCCEEDED"},
    {no: 4, name: "PLAN_STATE_FAILED", localName: "FAILED"},
  ],
);

/**
 * Moves any component on the robot to a specified destination which can be from the reference frame of any other component on the robot.
 *
 * @generated from message viam.service.motion.v1.MoveRequest
 */
export const MoveRequest = /*@__PURE__*/ proto3.makeMessageType(
  "viam.service.motion.v1.MoveRequest",
  () => [
    { no: 1, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "destination", kind: "message", T: PoseInFrame },
    { no: 3, name: "component_name_deprecated", kind: "message", T: ResourceName },
    { no: 4, name: "world_state", kind: "message", T: WorldState, opt: true },
    { no: 5, name: "constraints", kind: "message", T: Constraints, opt: true },
    { no: 6, name: "component_name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 99, name: "extra", kind: "message", T: Struct },
  ],
);

/**
 * @generated from message viam.service.motion.v1.MoveResponse
 */
export const MoveResponse = /*@__PURE__*/ proto3.makeMessageType(
  "viam.service.motion.v1.MoveResponse",
  () => [
    { no: 1, name: "success", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
  ],
);

/**
 * @generated from message viam.service.motion.v1.MoveOnMapRequest
 */
export const MoveOnMapRequest = /*@__PURE__*/ proto3.makeMessageType(
  "viam.service.motion.v1.MoveOnMapRequest",
  () => [
    { no: 1, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "destination", kind: "message", T: Pose },
    { no: 3, name: "component_name_deprecated", kind: "message", T: ResourceName },
    { no: 4, name: "slam_service_name_deprecated", kind: "message", T: ResourceName },
    { no: 5, name: "motion_configuration", kind: "message", T: MotionConfiguration, opt: true },
    { no: 6, name: "obstacles", kind: "message", T: Geometry, repeated: true },
    { no: 7, name: "component_name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 8, name: "slam_service_name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 99, name: "extra", kind: "message", T: Struct },
  ],
);

/**
 * @generated from message viam.service.motion.v1.MoveOnMapResponse
 */
export const MoveOnMapResponse = /*@__PURE__*/ proto3.makeMessageType(
  "viam.service.motion.v1.MoveOnMapResponse",
  () => [
    { no: 1, name: "execution_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * Pairs a vision service with a camera, informing the service about which camera it may use
 *
 * @generated from message viam.service.motion.v1.ObstacleDetector
 */
export const ObstacleDetector = /*@__PURE__*/ proto3.makeMessageType(
  "viam.service.motion.v1.ObstacleDetector",
  () => [
    { no: 1, name: "vision_service_deprecated", kind: "message", T: ResourceName },
    { no: 2, name: "camera_deprecated", kind: "message", T: ResourceName },
    { no: 3, name: "vision_service", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "camera", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message viam.service.motion.v1.MotionConfiguration
 */
export const MotionConfiguration = /*@__PURE__*/ proto3.makeMessageType(
  "viam.service.motion.v1.MotionConfiguration",
  () => [
    { no: 1, name: "obstacle_detectors", kind: "message", T: ObstacleDetector, repeated: true },
    { no: 2, name: "position_polling_frequency_hz", kind: "scalar", T: 1 /* ScalarType.DOUBLE */, opt: true },
    { no: 3, name: "obstacle_polling_frequency_hz", kind: "scalar", T: 1 /* ScalarType.DOUBLE */, opt: true },
    { no: 4, name: "plan_deviation_m", kind: "scalar", T: 1 /* ScalarType.DOUBLE */, opt: true },
    { no: 5, name: "linear_m_per_sec", kind: "scalar", T: 1 /* ScalarType.DOUBLE */, opt: true },
    { no: 6, name: "angular_degs_per_sec", kind: "scalar", T: 1 /* ScalarType.DOUBLE */, opt: true },
  ],
);

/**
 * @generated from message viam.service.motion.v1.MoveOnGlobeRequest
 */
export const MoveOnGlobeRequest = /*@__PURE__*/ proto3.makeMessageType(
  "viam.service.motion.v1.MoveOnGlobeRequest",
  () => [
    { no: 1, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "destination", kind: "message", T: GeoPoint },
    { no: 3, name: "heading", kind: "scalar", T: 1 /* ScalarType.DOUBLE */, opt: true },
    { no: 4, name: "component_name_deprecated", kind: "message", T: ResourceName },
    { no: 5, name: "movement_sensor_name_deprecated", kind: "message", T: ResourceName },
    { no: 6, name: "obstacles", kind: "message", T: GeoGeometry, repeated: true },
    { no: 7, name: "motion_configuration", kind: "message", T: MotionConfiguration, opt: true },
    { no: 8, name: "bounding_regions", kind: "message", T: GeoGeometry, repeated: true },
    { no: 9, name: "component_name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 10, name: "movement_sensor_name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 99, name: "extra", kind: "message", T: Struct },
  ],
);

/**
 * @generated from message viam.service.motion.v1.MoveOnGlobeResponse
 */
export const MoveOnGlobeResponse = /*@__PURE__*/ proto3.makeMessageType(
  "viam.service.motion.v1.MoveOnGlobeResponse",
  () => [
    { no: 1, name: "execution_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message viam.service.motion.v1.GetPoseRequest
 * @deprecated
 */
export const GetPoseRequest = /*@__PURE__*/ proto3.makeMessageType(
  "viam.service.motion.v1.GetPoseRequest",
  () => [
    { no: 1, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "component_name_deprecated", kind: "message", T: ResourceName },
    { no: 3, name: "destination_frame", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "supplemental_transforms", kind: "message", T: Transform, repeated: true },
    { no: 5, name: "component_name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 99, name: "extra", kind: "message", T: Struct },
  ],
);

/**
 * @generated from message viam.service.motion.v1.GetPoseResponse
 * @deprecated
 */
export const GetPoseResponse = /*@__PURE__*/ proto3.makeMessageType(
  "viam.service.motion.v1.GetPoseResponse",
  () => [
    { no: 1, name: "pose", kind: "message", T: PoseInFrame },
  ],
);

/**
 * @generated from message viam.service.motion.v1.StopPlanRequest
 */
export const StopPlanRequest = /*@__PURE__*/ proto3.makeMessageType(
  "viam.service.motion.v1.StopPlanRequest",
  () => [
    { no: 1, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "component_name_deprecated", kind: "message", T: ResourceName },
    { no: 3, name: "component_name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 99, name: "extra", kind: "message", T: Struct },
  ],
);

/**
 * @generated from message viam.service.motion.v1.StopPlanResponse
 */
export const StopPlanResponse = /*@__PURE__*/ proto3.makeMessageType(
  "viam.service.motion.v1.StopPlanResponse",
  [],
);

/**
 * @generated from message viam.service.motion.v1.ListPlanStatusesRequest
 */
export const ListPlanStatusesRequest = /*@__PURE__*/ proto3.makeMessageType(
  "viam.service.motion.v1.ListPlanStatusesRequest",
  () => [
    { no: 1, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "only_active_plans", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 99, name: "extra", kind: "message", T: Struct },
  ],
);

/**
 * Status of all executed / executing plan statuses with associated IDs within the 24 hour TTL
 *
 * @generated from message viam.service.motion.v1.ListPlanStatusesResponse
 */
export const ListPlanStatusesResponse = /*@__PURE__*/ proto3.makeMessageType(
  "viam.service.motion.v1.ListPlanStatusesResponse",
  () => [
    { no: 1, name: "plan_statuses_with_ids", kind: "message", T: PlanStatusWithID, repeated: true },
  ],
);

/**
 * @generated from message viam.service.motion.v1.GetPlanRequest
 */
export const GetPlanRequest = /*@__PURE__*/ proto3.makeMessageType(
  "viam.service.motion.v1.GetPlanRequest",
  () => [
    { no: 1, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "component_name_deprecated", kind: "message", T: ResourceName },
    { no: 3, name: "last_plan_only", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 4, name: "execution_id", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 5, name: "component_name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 99, name: "extra", kind: "message", T: Struct },
  ],
);

/**
 * @generated from message viam.service.motion.v1.GetPlanResponse
 */
export const GetPlanResponse = /*@__PURE__*/ proto3.makeMessageType(
  "viam.service.motion.v1.GetPlanResponse",
  () => [
    { no: 1, name: "current_plan_with_status", kind: "message", T: PlanWithStatus },
    { no: 2, name: "replan_history", kind: "message", T: PlanWithStatus, repeated: true },
  ],
);

/**
 * Constraints specifies all enumerated constraints to be passed to Viam's motion planning, along with any optional parameters
 *
 * @generated from message viam.service.motion.v1.Constraints
 */
export const Constraints = /*@__PURE__*/ proto3.makeMessageType(
  "viam.service.motion.v1.Constraints",
  () => [
    { no: 1, name: "linear_constraint", kind: "message", T: LinearConstraint, repeated: true },
    { no: 2, name: "orientation_constraint", kind: "message", T: OrientationConstraint, repeated: true },
    { no: 3, name: "collision_specification", kind: "message", T: CollisionSpecification, repeated: true },
    { no: 4, name: "pseudolinear_constraint", kind: "message", T: PseudolinearConstraint, repeated: true },
  ],
);

/**
 * LinearConstraint specifies that the component being moved should move linearly relative to its goal.
 * It does not constrain the motion of components other than the `component_name` specified in motion.Move
 *
 * @generated from message viam.service.motion.v1.LinearConstraint
 */
export const LinearConstraint = /*@__PURE__*/ proto3.makeMessageType(
  "viam.service.motion.v1.LinearConstraint",
  () => [
    { no: 1, name: "line_tolerance_mm", kind: "scalar", T: 2 /* ScalarType.FLOAT */, opt: true },
    { no: 2, name: "orientation_tolerance_degs", kind: "scalar", T: 2 /* ScalarType.FLOAT */, opt: true },
  ],
);

/**
 * PseudolinearConstraint specifies that the component being moved should not deviate from the straight-line path to their goal by
 * more than a factor proportional to the distance from start to goal.
 * For example, if a component is moving 100mm, then a LineToleranceFactor of 1.0 means that the component will remain within a 100mm
 * radius of the straight-line start-goal path.
 *
 * @generated from message viam.service.motion.v1.PseudolinearConstraint
 */
export const PseudolinearConstraint = /*@__PURE__*/ proto3.makeMessageType(
  "viam.service.motion.v1.PseudolinearConstraint",
  () => [
    { no: 1, name: "line_tolerance_factor", kind: "scalar", T: 2 /* ScalarType.FLOAT */, opt: true },
    { no: 2, name: "orientation_tolerance_factor", kind: "scalar", T: 2 /* ScalarType.FLOAT */, opt: true },
  ],
);

/**
 * OrientationConstraint specifies that the component being moved will not deviate its orientation beyond some threshold relative
 * to the goal. It does not constrain the motion of components other than the `component_name` specified in motion.Move
 *
 * @generated from message viam.service.motion.v1.OrientationConstraint
 */
export const OrientationConstraint = /*@__PURE__*/ proto3.makeMessageType(
  "viam.service.motion.v1.OrientationConstraint",
  () => [
    { no: 1, name: "orientation_tolerance_degs", kind: "scalar", T: 2 /* ScalarType.FLOAT */, opt: true },
  ],
);

/**
 * CollisionSpecification is used to selectively apply obstacle avoidance to specific parts of the robot
 *
 * @generated from message viam.service.motion.v1.CollisionSpecification
 */
export const CollisionSpecification = /*@__PURE__*/ proto3.makeMessageType(
  "viam.service.motion.v1.CollisionSpecification",
  () => [
    { no: 1, name: "allows", kind: "message", T: CollisionSpecification_AllowedFrameCollisions, repeated: true },
  ],
);

/**
 * @generated from message viam.service.motion.v1.CollisionSpecification.AllowedFrameCollisions
 */
export const CollisionSpecification_AllowedFrameCollisions = /*@__PURE__*/ proto3.makeMessageType(
  "viam.service.motion.v1.CollisionSpecification.AllowedFrameCollisions",
  () => [
    { no: 1, name: "frame1", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "frame2", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
  {localName: "CollisionSpecification_AllowedFrameCollisions"},
);

/**
 * Describes a plan, its current status & all status changes
 * that have occured previously on that plan
 *
 * @generated from message viam.service.motion.v1.PlanWithStatus
 */
export const PlanWithStatus = /*@__PURE__*/ proto3.makeMessageType(
  "viam.service.motion.v1.PlanWithStatus",
  () => [
    { no: 1, name: "plan", kind: "message", T: Plan },
    { no: 2, name: "status", kind: "message", T: PlanStatus },
    { no: 3, name: "status_history", kind: "message", T: PlanStatus, repeated: true },
  ],
);

/**
 * PlanStatusWithID describes the state of a given plan at a
 * point in time plus the plan_id, component_name and execution_id
 * the status is associated with
 *
 * @generated from message viam.service.motion.v1.PlanStatusWithID
 */
export const PlanStatusWithID = /*@__PURE__*/ proto3.makeMessageType(
  "viam.service.motion.v1.PlanStatusWithID",
  () => [
    { no: 1, name: "plan_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "component_name_deprecated", kind: "message", T: ResourceName },
    { no: 3, name: "execution_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "status", kind: "message", T: PlanStatus },
    { no: 5, name: "component_name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * Plan status describes the state of a given plan at a
 * point in time
 *
 * @generated from message viam.service.motion.v1.PlanStatus
 */
export const PlanStatus = /*@__PURE__*/ proto3.makeMessageType(
  "viam.service.motion.v1.PlanStatus",
  () => [
    { no: 1, name: "state", kind: "enum", T: proto3.getEnumType(PlanState) },
    { no: 2, name: "timestamp", kind: "message", T: Timestamp },
    { no: 3, name: "reason", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
  ],
);

/**
 * A plan describes a motion plan
 *
 * @generated from message viam.service.motion.v1.Plan
 */
export const Plan = /*@__PURE__*/ proto3.makeMessageType(
  "viam.service.motion.v1.Plan",
  () => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "component_name_deprecated", kind: "message", T: ResourceName },
    { no: 3, name: "execution_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "steps", kind: "message", T: PlanStep, repeated: true },
    { no: 5, name: "component_name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message viam.service.motion.v1.PlanStep
 */
export const PlanStep = /*@__PURE__*/ proto3.makeMessageType(
  "viam.service.motion.v1.PlanStep",
  () => [
    { no: 1, name: "step", kind: "map", K: 9 /* ScalarType.STRING */, V: {kind: "message", T: ComponentState} },
  ],
);

/**
 * A pose
 *
 * @generated from message viam.service.motion.v1.ComponentState
 */
export const ComponentState = /*@__PURE__*/ proto3.makeMessageType(
  "viam.service.motion.v1.ComponentState",
  () => [
    { no: 1, name: "pose", kind: "message", T: Pose },
  ],
);

