// @generated by protoc-gen-connect-es v1.6.1
// @generated from file component/movementsensor/v1/movementsensor.proto (package viam.component.movementsensor.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { GetAccuracyRequest, GetAccuracyResponse, GetAngularVelocityRequest, GetAngularVelocityResponse, GetCompassHeadingRequest, GetCompassHeadingResponse, GetLinearAccelerationRequest, GetLinearAccelerationResponse, GetLinearVelocityRequest, GetLinearVelocityResponse, GetOrientationRequest, GetOrientationResponse, GetPositionRequest, GetPositionResponse, GetPropertiesRequest, GetPropertiesResponse } from "./movementsensor_pb.js";
import { MethodKind } from "@bufbuild/protobuf";
import { DoCommandRequest, DoCommandResponse, GetGeometriesRequest, GetGeometriesResponse, GetReadingsRequest, GetReadingsResponse, GetStatusRequest, GetStatusResponse } from "../../../common/v1/common_pb.js";

/**
 * @generated from service viam.component.movementsensor.v1.MovementSensorService
 */
export const MovementSensorService = {
  typeName: "viam.component.movementsensor.v1.MovementSensorService",
  methods: {
    /**
     * @generated from rpc viam.component.movementsensor.v1.MovementSensorService.GetLinearVelocity
     */
    getLinearVelocity: {
      name: "GetLinearVelocity",
      I: GetLinearVelocityRequest,
      O: GetLinearVelocityResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc viam.component.movementsensor.v1.MovementSensorService.GetAngularVelocity
     */
    getAngularVelocity: {
      name: "GetAngularVelocity",
      I: GetAngularVelocityRequest,
      O: GetAngularVelocityResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc viam.component.movementsensor.v1.MovementSensorService.GetCompassHeading
     */
    getCompassHeading: {
      name: "GetCompassHeading",
      I: GetCompassHeadingRequest,
      O: GetCompassHeadingResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc viam.component.movementsensor.v1.MovementSensorService.GetOrientation
     */
    getOrientation: {
      name: "GetOrientation",
      I: GetOrientationRequest,
      O: GetOrientationResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc viam.component.movementsensor.v1.MovementSensorService.GetPosition
     */
    getPosition: {
      name: "GetPosition",
      I: GetPositionRequest,
      O: GetPositionResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc viam.component.movementsensor.v1.MovementSensorService.GetProperties
     */
    getProperties: {
      name: "GetProperties",
      I: GetPropertiesRequest,
      O: GetPropertiesResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc viam.component.movementsensor.v1.MovementSensorService.GetAccuracy
     */
    getAccuracy: {
      name: "GetAccuracy",
      I: GetAccuracyRequest,
      O: GetAccuracyResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc viam.component.movementsensor.v1.MovementSensorService.GetLinearAcceleration
     */
    getLinearAcceleration: {
      name: "GetLinearAcceleration",
      I: GetLinearAccelerationRequest,
      O: GetLinearAccelerationResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc viam.component.movementsensor.v1.MovementSensorService.DoCommand
     */
    doCommand: {
      name: "DoCommand",
      I: DoCommandRequest,
      O: DoCommandResponse,
      kind: MethodKind.Unary,
    },
    /**
     * GetStatus returns the status of the resource
     *
     * @generated from rpc viam.component.movementsensor.v1.MovementSensorService.GetStatus
     */
    getStatus: {
      name: "GetStatus",
      I: GetStatusRequest,
      O: GetStatusResponse,
      kind: MethodKind.Unary,
    },
    /**
     * GetGeometries returns the geometries of the component in their current configuration
     *
     * @generated from rpc viam.component.movementsensor.v1.MovementSensorService.GetGeometries
     */
    getGeometries: {
      name: "GetGeometries",
      I: GetGeometriesRequest,
      O: GetGeometriesResponse,
      kind: MethodKind.Unary,
    },
    /**
     * GetReadings returns the readings of a sensor of the underlying robot.
     *
     * @generated from rpc viam.component.movementsensor.v1.MovementSensorService.GetReadings
     */
    getReadings: {
      name: "GetReadings",
      I: GetReadingsRequest,
      O: GetReadingsResponse,
      kind: MethodKind.Unary,
    },
  }
};

