// @generated by protoc-gen-connect-es v1.6.1
// @generated from file proto/rpc/examples/echoresource/v1/echoresource.proto (package proto.rpc.examples.echoresource.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { EchoResourceBiDiRequest, EchoResourceBiDiResponse, EchoResourceMultipleRequest, EchoResourceMultipleResponse, EchoResourceRequest, EchoResourceResponse } from "./echoresource_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service proto.rpc.examples.echoresource.v1.EchoResourceService
 */
export const EchoResourceService = {
  typeName: "proto.rpc.examples.echoresource.v1.EchoResourceService",
  methods: {
    /**
     * @generated from rpc proto.rpc.examples.echoresource.v1.EchoResourceService.EchoResource
     */
    echoResource: {
      name: "EchoResource",
      I: EchoResourceRequest,
      O: EchoResourceResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc proto.rpc.examples.echoresource.v1.EchoResourceService.EchoResourceMultiple
     */
    echoResourceMultiple: {
      name: "EchoResourceMultiple",
      I: EchoResourceMultipleRequest,
      O: EchoResourceMultipleResponse,
      kind: MethodKind.ServerStreaming,
    },
    /**
     * @generated from rpc proto.rpc.examples.echoresource.v1.EchoResourceService.EchoResourceBiDi
     */
    echoResourceBiDi: {
      name: "EchoResourceBiDi",
      I: EchoResourceBiDiRequest,
      O: EchoResourceBiDiResponse,
      kind: MethodKind.BiDiStreaming,
    },
  }
};

