// @generated by protoc-gen-connect-es v1.6.1
// @generated from file proto/rpc/examples/echoresource/v1/echoresource.proto (package proto.rpc.examples.echoresource.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { EchoResourceBiDiRequest, EchoResourceBiDiResponse, EchoResourceMultipleRequest, EchoResourceMultipleResponse, EchoResourceRequest, EchoResourceResponse } from "./echoresource_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service proto.rpc.examples.echoresource.v1.EchoResourceService
 */
export declare const EchoResourceService: {
  readonly typeName: "proto.rpc.examples.echoresource.v1.EchoResourceService",
  readonly methods: {
    /**
     * @generated from rpc proto.rpc.examples.echoresource.v1.EchoResourceService.EchoResource
     */
    readonly echoResource: {
      readonly name: "EchoResource",
      readonly I: typeof EchoResourceRequest,
      readonly O: typeof EchoResourceResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc proto.rpc.examples.echoresource.v1.EchoResourceService.EchoResourceMultiple
     */
    readonly echoResourceMultiple: {
      readonly name: "EchoResourceMultiple",
      readonly I: typeof EchoResourceMultipleRequest,
      readonly O: typeof EchoResourceMultipleResponse,
      readonly kind: MethodKind.ServerStreaming,
    },
    /**
     * @generated from rpc proto.rpc.examples.echoresource.v1.EchoResourceService.EchoResourceBiDi
     */
    readonly echoResourceBiDi: {
      readonly name: "EchoResourceBiDi",
      readonly I: typeof EchoResourceBiDiRequest,
      readonly O: typeof EchoResourceBiDiResponse,
      readonly kind: MethodKind.BiDiStreaming,
    },
  }
};

